CREATE TABLE "agente_nocivo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agente_nocivo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"descricao" varchar(200) NOT NULL,
	"tipo_risco_id" integer NOT NULL,
	"fundamentacao_id" integer,
	"percentual_sugerido_id" integer,
	"exige_reavaliacao_quantitativa" boolean DEFAULT false NOT NULL,
	"agente_canonico_id" integer,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "agente_nocivo_descricao_unique" UNIQUE("descricao")
);
--> statement-breakpoint
CREATE TABLE "checklist_modelo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "checklist_modelo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"tipo_processo_id" integer,
	"estado_alvo" varchar(32),
	"itens" text NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "checklist_modelo_nome_unique" UNIQUE("nome")
);
--> statement-breakpoint
CREATE TABLE "fluxo_etapa" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fluxo_etapa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(30) NOT NULL,
	"nome" varchar(60) NOT NULL,
	"ordem" smallint NOT NULL,
	"tipo" varchar(12) DEFAULT 'FLUXO' NOT NULL,
	"terminal" boolean DEFAULT false NOT NULL,
	CONSTRAINT "fluxo_etapa_codigo_unique" UNIQUE("codigo"),
	CONSTRAINT "fluxo_etapa_ordem_unique" UNIQUE("ordem"),
	CONSTRAINT "ck_etapa_tipo" CHECK (tipo IN ('FLUXO','REPOSITORIO'))
);
--> statement-breakpoint
CREATE TABLE "fundamentacao_legal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fundamentacao_legal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(30) NOT NULL,
	"norma" varchar(40) NOT NULL,
	"anexo" varchar(20),
	"tipo_risco_id" integer,
	"texto" text NOT NULL,
	"dispositivo_conferido_em" date,
	"vigente" boolean DEFAULT true NOT NULL,
	CONSTRAINT "fundamentacao_legal_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "parametro" (
	"chave" varchar(60) PRIMARY KEY NOT NULL,
	"valor" text NOT NULL,
	"descricao" text
);
--> statement-breakpoint
CREATE TABLE "percentual_aplicavel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "percentual_aplicavel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tipo_adicional_id" integer NOT NULL,
	"grau" varchar(10) NOT NULL,
	"rotulo" varchar(40) NOT NULL,
	"valor" numeric(5, 2) NOT NULL,
	"base_calculo" varchar(60) DEFAULT 'vencimento do cargo efetivo' NOT NULL,
	CONSTRAINT "uq_percentual" UNIQUE("tipo_adicional_id","grau"),
	CONSTRAINT "ck_grau" CHECK (grau IN ('MINIMO','MEDIO','MAXIMO','UNICO'))
);
--> statement-breakpoint
CREATE TABLE "texto_padrao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "texto_padrao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria" varchar(30) NOT NULL,
	"codigo" varchar(40) NOT NULL,
	"template" text NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	"vigente" boolean DEFAULT true NOT NULL,
	"renderizado_pelo_modelo" boolean DEFAULT true NOT NULL,
	"dispositivo_conferido_em" date,
	CONSTRAINT "uq_texto" UNIQUE("categoria","codigo","versao"),
	CONSTRAINT "ck_cat" CHECK (categoria IN ('ALTERACAO','RECOMENDACAO','REAVALIACAO','RODAPE_RESPONSABILIDADE','ASSUNTO','PREAMBULO','ENCERRAMENTO'))
);
--> statement-breakpoint
CREATE TABLE "tipo_adicional" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tipo_adicional_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(24) NOT NULL,
	"nome" varchar(80) NOT NULL,
	"nome_recomendacao" varchar(80) NOT NULL,
	"base_legal" text,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "tipo_adicional_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "tipo_marco_inicial" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tipo_marco_inicial_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(30) NOT NULL,
	"rotulo" varchar(80) NOT NULL,
	"base_legal" text,
	CONSTRAINT "tipo_marco_inicial_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "tipo_movimento" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tipo_movimento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(20) NOT NULL,
	"nome" varchar(40) NOT NULL,
	"gera_direito" boolean DEFAULT true NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "tipo_movimento_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "tipo_processo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tipo_processo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(30) NOT NULL,
	"nome" varchar(80) NOT NULL,
	"cor_hex" varchar(7),
	"modulo" varchar(32) DEFAULT 'ADICIONAL' NOT NULL,
	CONSTRAINT "tipo_processo_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "tipo_risco" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tipo_risco_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(20) NOT NULL,
	"nome" varchar(60) NOT NULL,
	CONSTRAINT "tipo_risco_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "campus" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campus_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sigla" varchar(12) NOT NULL,
	"nome" varchar(120) NOT NULL,
	"cidade" varchar(80) NOT NULL,
	"uf" varchar(2) DEFAULT 'MG' NOT NULL,
	"avancado" boolean DEFAULT false NOT NULL,
	CONSTRAINT "campus_sigla_unique" UNIQUE("sigla")
);
--> statement-breakpoint
CREATE TABLE "cargo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cargo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"codigo_siape" varchar(10),
	CONSTRAINT "cargo_nome_unique" UNIQUE("nome")
);
--> statement-breakpoint
CREATE TABLE "lotacao_posto" (
	"lotacao_id" integer NOT NULL,
	"posto_trabalho_id" integer NOT NULL,
	"ordem" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "lotacao_posto_lotacao_id_posto_trabalho_id_pk" PRIMARY KEY("lotacao_id","posto_trabalho_id")
);
--> statement-breakpoint
CREATE TABLE "portaria_localizacao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portaria_localizacao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unidade_emissora_id" integer NOT NULL,
	"numero" varchar(10) NOT NULL,
	"ano" integer NOT NULL,
	"data_publicacao" date NOT NULL,
	"texto_original" text NOT NULL,
	"arquivo_anexo_id" integer,
	CONSTRAINT "uq_portaria" UNIQUE("unidade_emissora_id","numero","ano"),
	CONSTRAINT "ck_portaria_ano" CHECK (EXTRACT(YEAR FROM data_publicacao) = ano)
);
--> statement-breakpoint
CREATE TABLE "portaria_servidor" (
	"portaria_id" integer NOT NULL,
	"servidor_id" integer NOT NULL,
	"posto_trabalho_id" integer,
	CONSTRAINT "portaria_servidor_portaria_id_servidor_id_pk" PRIMARY KEY("portaria_id","servidor_id")
);
--> statement-breakpoint
CREATE TABLE "posto_trabalho" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posto_trabalho_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unidade_uorg_id" integer NOT NULL,
	"nome" varchar(180) NOT NULL,
	"sigla" varchar(20),
	"descricao" text,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "uq_posto" UNIQUE("unidade_uorg_id","nome")
);
--> statement-breakpoint
CREATE TABLE "servidor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "servidor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"siape" varchar(7) NOT NULL,
	"nome" varchar(160) NOT NULL,
	"cargo_id" integer,
	"funcao" varchar(120),
	"unidade_uorg_id" integer,
	"uorg_id" integer,
	"situacao" varchar(20) DEFAULT 'ATIVO' NOT NULL,
	"email" varchar(160),
	CONSTRAINT "servidor_siape_unique" UNIQUE("siape"),
	CONSTRAINT "ck_siape" CHECK (siape ~ '^(?:\d{7})$')
);
--> statement-breakpoint
CREATE TABLE "servidor_lotacao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "servidor_lotacao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"servidor_id" integer NOT NULL,
	"unidade_uorg_id" integer,
	"uorg_id" integer,
	"cargo_id" integer,
	"funcao" varchar(120),
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date,
	"documento" varchar(200),
	"observacao" text,
	"registrado_por" integer,
	CONSTRAINT "uq_lotacao_inicio" UNIQUE("servidor_id","vigencia_inicio"),
	CONSTRAINT "ck_lotacao_periodo" CHECK (vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);
--> statement-breakpoint
CREATE TABLE "unidade_uorg" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unidade_uorg_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo_uorg" varchar(6),
	"sigla" varchar(20),
	"nome_oficial" varchar(160) NOT NULL,
	"nome_extenso" varchar(160) NOT NULL,
	"tipo" varchar(20) NOT NULL,
	"unidade_pai_id" integer,
	"campus_id" integer NOT NULL,
	"emite_portaria" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unidade_uorg_codigo_uorg_unique" UNIQUE("codigo_uorg"),
	CONSTRAINT "ck_uorg_tipo" CHECK (tipo IN ('FACULDADE','INSTITUTO','DEPARTAMENTO','PRO_REITORIA','DIRETORIA','COORDENADORIA','SUPERINTENDENCIA','SECRETARIA','OUTRO'))
);
--> statement-breakpoint
CREATE TABLE "acesso_dado_sensivel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "acesso_dado_sensivel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario_id" integer NOT NULL,
	"servidor_id" integer,
	"processo_id" integer,
	"campo" varchar(60) NOT NULL,
	"finalidade" text,
	"ocorrido_em" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "atribuicao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "atribuicao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario_id" integer NOT NULL,
	"perfil_id" integer NOT NULL,
	"coordenadoria" varchar(16) DEFAULT 'CSSO' NOT NULL,
	"campus_id" integer,
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date,
	"ato_normativo" text,
	"concedido_por" integer
);
--> statement-breakpoint
CREATE TABLE "autoridade_destinataria" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "autoridade_destinataria_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(160) NOT NULL,
	"cargo" varchar(120) NOT NULL,
	"tratamento" varchar(80) NOT NULL,
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date
);
--> statement-breakpoint
CREATE TABLE "perfil" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "perfil_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(32) NOT NULL,
	"nome" varchar(80) NOT NULL,
	"base_normativa" text,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "perfil_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "perfil_permissao" (
	"perfil_id" integer NOT NULL,
	"permissao_id" integer NOT NULL,
	CONSTRAINT "perfil_permissao_perfil_id_permissao_id_pk" PRIMARY KEY("perfil_id","permissao_id")
);
--> statement-breakpoint
CREATE TABLE "permissao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(64) NOT NULL,
	"modulo" varchar(32) DEFAULT 'ADICIONAL' NOT NULL,
	"descricao" text NOT NULL,
	CONSTRAINT "permissao_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "profissional_habilitado" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "profissional_habilitado_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario_id" integer,
	"servidor_id" integer,
	"nome" varchar(160) NOT NULL,
	"siape" varchar(7),
	"habilitacao" varchar(30) NOT NULL,
	"titulo_assinatura" varchar(60) NOT NULL,
	"conselho" varchar(8),
	"registro_conselho" varchar(30),
	"documento_especializacao" varchar(120),
	"externo" boolean DEFAULT false NOT NULL,
	"justificativa_art10_par5" text,
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date,
	"atestado_por" integer,
	"atestado_em" timestamp with time zone,
	CONSTRAINT "ck_habilitacao" CHECK (habilitacao IN ('MED_TRABALHO','ENG_SEG_TRABALHO','ARQ_SEG_TRABALHO')),
	CONSTRAINT "ck_externo" CHECK (NOT externo OR justificativa_art10_par5 IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "sessao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" varchar(64) NOT NULL,
	"usuario_id" integer NOT NULL,
	"criada_em" timestamp with time zone NOT NULL,
	"expira_em" timestamp with time zone NOT NULL,
	"ip" text,
	"user_agent" text,
	"revogada" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sessao_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "setor_emissor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "setor_emissor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sigla_composta" varchar(60) NOT NULL,
	"nome_extenso" varchar(200) NOT NULL,
	"unidade_sei" varchar(40),
	"email" varchar(160),
	"endereco" text,
	"cidade" varchar(80) DEFAULT 'Diamantina' NOT NULL,
	"telefone" varchar(60),
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date,
	"base_normativa" text,
	CONSTRAINT "uq_setor_vigencia" UNIQUE("sigla_composta","vigencia_inicio")
);
--> statement-breakpoint
CREATE TABLE "usuario" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuario_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"login" varchar(64) NOT NULL,
	"nome" varchar(160) NOT NULL,
	"email" varchar(160) NOT NULL,
	"senha_hash" varchar(255) NOT NULL,
	"provedor" varchar(16) DEFAULT 'LOCAL' NOT NULL,
	"identificador_externo" varchar(120),
	"servidor_id" integer,
	"precisa_trocar_senha" boolean DEFAULT true NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"tentativas_falhas" smallint DEFAULT 0 NOT NULL,
	"bloqueado_ate" timestamp with time zone,
	"ultimo_login_em" timestamp with time zone,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "usuario_login_unique" UNIQUE("login"),
	CONSTRAINT "usuario_email_unique" UNIQUE("email"),
	CONSTRAINT "ck_usuario_provedor" CHECK (provedor IN ('LOCAL','LDAP','SSO_UFVJM'))
);
--> statement-breakpoint
CREATE TABLE "adicional_vigencia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "adicional_vigencia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"servidor_id" integer NOT NULL,
	"parecer_id" integer NOT NULL,
	"tipo_adicional_id" integer NOT NULL,
	"percentual_id" integer NOT NULL,
	"estado" varchar(16) DEFAULT 'PROPOSTO' NOT NULL,
	"portaria_concessao" varchar(120),
	"data_portaria_concessao" date,
	"data_inicio" date,
	"data_fim" date,
	"motivo_suspensao" varchar(30),
	"base_legal_suspensao" varchar(120),
	"registro_opcao_anexo_id" integer,
	CONSTRAINT "ck_estado" CHECK (estado IN ('PROPOSTO','VIGENTE','SUSPENSO','EM_REAVALIACAO','ALTERADO','CESSADO')),
	CONSTRAINT "ck_motivo_susp" CHECK (motivo_suspensao IS NULL OR motivo_suspensao IN ('CESSACAO_RISCO','AFASTAMENTO_DO_LOCAL','AFASTAMENTO_LEGAL','DECISAO_ADMINISTRATIVA'))
);
--> statement-breakpoint
CREATE TABLE "exposicao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "exposicao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"parecer_id" integer NOT NULL,
	"agente_nocivo_id" integer NOT NULL,
	"percentual_id" integer NOT NULL,
	"fundamentacao_id" integer NOT NULL,
	"posto_trabalho_id" integer,
	"principal" boolean DEFAULT false NOT NULL,
	"tempo_exposicao" varchar(60),
	"horas_exposicao_mensais" numeric(6, 2),
	"jornada_mensal_horas" numeric(6, 2),
	"percentual_jornada" numeric(5, 2),
	"classificacao_exposicao" varchar(16),
	"classificacao_origem" varchar(10) DEFAULT 'CALCULADA' NOT NULL,
	"excecao_art9_par_unico" boolean DEFAULT false NOT NULL,
	"justificativa_art9" text,
	"intensidade" numeric(12, 4),
	"unidade_medida" varchar(20),
	"limite_tolerancia" numeric(12, 4),
	"metodologia" varchar(120),
	"data_avaliacao" date,
	"epi_neutraliza" varchar(20) DEFAULT 'NAO_AVALIADO' NOT NULL,
	"justificativa_epi" text,
	"epi_avaliado_em" date,
	CONSTRAINT "uq_exposicao" UNIQUE("parecer_id","agente_nocivo_id"),
	CONSTRAINT "ck_exposicao" CHECK (classificacao_exposicao IS NULL OR classificacao_exposicao IN ('EVENTUAL','HABITUAL','PERMANENTE')),
	CONSTRAINT "ck_excecao" CHECK (NOT excecao_art9_par_unico OR justificativa_art9 IS NOT NULL),
	CONSTRAINT "ck_class_origem" CHECK (classificacao_origem IN ('CALCULADA','INFORMADA')),
	CONSTRAINT "ck_exposicao_epi" CHECK (epi_neutraliza IN ('NAO_AVALIADO','NAO_NEUTRALIZA','NEUTRALIZA_PARCIAL','NEUTRALIZA')),
	CONSTRAINT "ck_exposicao_epi_justificada" CHECK (epi_neutraliza IN ('NAO_AVALIADO','NAO_NEUTRALIZA') OR justificativa_epi IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "laudo_posto" (
	"laudo_id" integer NOT NULL,
	"posto_trabalho_id" integer NOT NULL,
	CONSTRAINT "laudo_posto_laudo_id_posto_trabalho_id_pk" PRIMARY KEY("laudo_id","posto_trabalho_id")
);
--> statement-breakpoint
CREATE TABLE "laudo_tecnico" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "laudo_tecnico_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"numero_siape" varchar(20) NOT NULL,
	"ano" integer NOT NULL,
	"tipo_adicional_id" integer NOT NULL,
	"coletivo" boolean DEFAULT false NOT NULL,
	"unidade_uorg_id" integer NOT NULL,
	"data_emissao" date,
	"data_avaliacao" date,
	"data_ultima_conferencia" date,
	"motivo_ultima_conferencia" text,
	"subscritor_id" integer,
	"processo_id" integer,
	"numero_documento_sei" varchar(10),
	"status" varchar(10) DEFAULT 'VIGENTE' NOT NULL,
	"substituido_por_id" integer,
	"observacoes" text,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "laudo_tecnico_numero_siape_unique" UNIQUE("numero_siape"),
	CONSTRAINT "ck_laudo_fmt" CHECK (numero_siape ~ '^(?:\d{5}-\d{3}\.\d{3}/\d{4})$'),
	CONSTRAINT "ck_laudo_ano" CHECK (CASE WHEN substr(numero_siape,15,4) ~ '^[0-9]{4}$' THEN ano = CAST(substr(numero_siape,15,4) AS integer) ELSE false END),
	CONSTRAINT "ck_laudo_status" CHECK (status IN ('VIGENTE','SUPERADO'))
);
--> statement-breakpoint
CREATE TABLE "parecer_posto" (
	"parecer_id" integer NOT NULL,
	"posto_trabalho_id" integer NOT NULL,
	"ordem" smallint DEFAULT 1 NOT NULL,
	CONSTRAINT "parecer_posto_parecer_id_posto_trabalho_id_pk" PRIMARY KEY("parecer_id","posto_trabalho_id")
);
--> statement-breakpoint
CREATE TABLE "parecer_sequencia" (
	"ano" integer PRIMARY KEY NOT NULL,
	"ultimo_numero" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parecer_tecnico" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parecer_tecnico_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"numero" integer NOT NULL,
	"ano" integer NOT NULL,
	"data_emissao" date,
	"situacao" varchar(15) DEFAULT 'RASCUNHO' NOT NULL,
	"processo_id" integer,
	"servidor_id" integer,
	"laudo_id" integer,
	"tipo_adicional_id" integer,
	"tipo_movimento_id" integer,
	"unidade_uorg_id" integer,
	"uorg_id" integer,
	"portaria_id" integer,
	"destinatario_id" integer,
	"signatario_id" integer,
	"setor_emissor_id" integer,
	"campus_id" integer,
	"parecer_anterior_id" integer,
	"cargo_snapshot" varchar(120),
	"funcao_snapshot" varchar(120),
	"sigla_emissora_snapshot" varchar(60),
	"nome_emissor_snapshot" varchar(200),
	"endereco_emissor_snapshot" text,
	"telefone_emissor_snapshot" varchar(60),
	"tipo_marco_id" integer,
	"data_marco_inicial" date,
	"justificativa_marco" text,
	"texto_recomendacao" text,
	"texto_alteracao" text,
	"texto_reavaliacao" text,
	"texto_rodape" text,
	"texto_recomendacao_literal" boolean DEFAULT false NOT NULL,
	"modelo_arquivo" varchar(120),
	"modelo_sha256" varchar(64),
	"hash_conteudo" varchar(64),
	"contexto_congelado" jsonb,
	"horas_semanais_fonte" numeric(5, 2),
	"portaria_designacao_dirigente_id" integer,
	"area_radiologica" varchar(16),
	"arquivo_docx_id" integer,
	"arquivo_pdf_id" integer,
	"numero_documento_sei" varchar(10),
	"motivo_anulacao" text,
	"origem_migracao" varchar(20),
	"origem_ref" varchar(64),
	"ano_inferido" boolean DEFAULT false NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	"criado_por" integer,
	"criado_em" timestamp with time zone NOT NULL,
	"emitido_por" integer,
	"emitido_em" timestamp with time zone,
	"assinado_em" timestamp with time zone,
	CONSTRAINT "uq_parecer" UNIQUE("numero","ano"),
	CONSTRAINT "ck_situacao" CHECK (situacao IN ('RESERVADO','RASCUNHO','EM_REVISAO','EMITIDO','ASSINADO','ANULADO')),
	CONSTRAINT "ck_data_ano" CHECK (data_emissao IS NULL OR EXTRACT(YEAR FROM data_emissao) = ano),
	CONSTRAINT "ck_area" CHECK (area_radiologica IS NULL OR area_radiologica IN ('CONTROLADA','SUPERVISIONADA')),
	CONSTRAINT "ck_completo" CHECK (situacao NOT IN ('EMITIDO','ASSINADO') OR (servidor_id IS NOT NULL AND laudo_id IS NOT NULL AND data_emissao IS NOT NULL AND signatario_id IS NOT NULL AND destinatario_id IS NOT NULL AND portaria_id IS NOT NULL AND processo_id IS NOT NULL AND tipo_adicional_id IS NOT NULL AND tipo_movimento_id IS NOT NULL AND unidade_uorg_id IS NOT NULL AND texto_recomendacao IS NOT NULL AND tipo_marco_id IS NOT NULL AND data_marco_inicial IS NOT NULL)),
	CONSTRAINT "ck_anulado" CHECK (situacao <> 'ANULADO' OR motivo_anulacao IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "processo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "processo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nup" varchar(20) NOT NULL,
	"tipo_processo_id" integer NOT NULL,
	"etapa_id" integer NOT NULL,
	"estado_tecnico" varchar(32) DEFAULT 'RECEBIDO' NOT NULL,
	"estado_anterior" varchar(32),
	"servidor_id" integer,
	"unidade_uorg_id" integer,
	"responsavel_id" integer,
	"ano_referencia" integer,
	"data_solicitacao_sest" date,
	"data_autuacao" date,
	"prazo" date,
	"data_conclusao" date,
	"situacao" varchar(20) DEFAULT 'EM_ANDAMENTO' NOT NULL,
	"nivel_acesso" varchar(12) DEFAULT 'PUBLICO' NOT NULL,
	"acompanhamento_especial" boolean DEFAULT false NOT NULL,
	"pronto_para_emissao" boolean DEFAULT false NOT NULL,
	"origem_repositorio" boolean DEFAULT false NOT NULL,
	"url_permanente" text,
	"observacoes" text,
	"nup_dv_dispensado" boolean DEFAULT false NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	"origem_migracao" varchar(20),
	"origem_ref" varchar(64),
	"entrou_na_etapa_em" timestamp with time zone NOT NULL,
	"criado_em" timestamp with time zone NOT NULL,
	"atualizado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "processo_nup_unique" UNIQUE("nup"),
	CONSTRAINT "ck_nup_fmt" CHECK (nup ~ '^(?:23086\.\d{6}/\d{4}-\d{2})$'),
	CONSTRAINT "ck_acesso" CHECK (nivel_acesso IN ('PUBLICO','RESTRITO','SIGILOSO')),
	CONSTRAINT "ck_conclusao" CHECK ((situacao = 'CONCLUIDO') = (data_conclusao IS NOT NULL)),
	CONSTRAINT "ck_estado_tecnico" CHECK (estado_tecnico IN ('NAO_INICIADO','RECEBIDO','EM_TRIAGEM','PENDENTE_DOCUMENTO','AGUARDANDO_INSPECAO','INSPECIONADO','AGUARDANDO_QUANTIFICACAO','LAUDO_EM_ELABORACAO','LAUDO_EMITIDO','PARECER_EM_ELABORACAO','PARECER_PRONTO_P_ASSINATURA','PARECER_ASSINADO','INSERIDO_NO_SEI','DEVOLVIDO_A_PROGEP','CONCLUIDO','INDEFERIDO_TECNICAMENTE','ARQUIVADO','SOBRESTADO','EM_RECURSO'))
);
--> statement-breakpoint
CREATE TABLE "anexo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anexo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entidade" varchar(30) NOT NULL,
	"entidade_id" integer NOT NULL,
	"nome_arquivo" varchar(255) NOT NULL,
	"nome_original" varchar(255) NOT NULL,
	"mime_type" varchar(100) NOT NULL,
	"tamanho_bytes" bigint NOT NULL,
	"sha256" varchar(64) NOT NULL,
	"storage_key" text NOT NULL,
	"categoria" varchar(30) DEFAULT 'OUTRO' NOT NULL,
	"nivel_acesso" varchar(12) DEFAULT 'PUBLICO' NOT NULL,
	"numero_documento_sei" varchar(10),
	"assinado" boolean DEFAULT false NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"origem_migracao" varchar(20),
	"origem_ref" varchar(200),
	"enviado_por" integer,
	"enviado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "ck_anexo_cat" CHECK (categoria IN ('PARECER_ASSINADO','LAUDO','PORTARIA','DESPACHO','FORMULARIO','RELATORIO_CAMPO','FOTO','OUTRO','MANUAL_EPI','FICHA_EPI','RUBRICA_INSTRUTOR','LISTA_PRESENCA','CERTIFICADO','CAT_SP','RELATORIO_INVESTIGACAO','EVIDENCIA_ACIDENTE'))
);
--> statement-breakpoint
CREATE TABLE "checklist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "checklist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"processo_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"ordem" smallint DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "checklist_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "checklist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"checklist_id" integer NOT NULL,
	"descricao" varchar(255) NOT NULL,
	"concluido" boolean DEFAULT false NOT NULL,
	"concluido_em" timestamp with time zone,
	"concluido_por" integer,
	"ordem" smallint DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conferencia_cadeia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conferencia_cadeia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"iniciada_em" timestamp with time zone NOT NULL,
	"concluida_em" timestamp with time zone NOT NULL,
	"duracao_ms" integer NOT NULL,
	"eventos" integer NOT NULL,
	"ultimo_evento_id" bigint,
	"integra" boolean NOT NULL,
	"primeiro_defeito_id" bigint,
	"origem" varchar(10) NOT NULL,
	"usuario_id" integer,
	CONSTRAINT "ck_conferencia_origem" CHECK (origem IN ('BOTAO','ROTINA')),
	CONSTRAINT "ck_conferencia_defeito" CHECK ((integra AND primeiro_defeito_id IS NULL) OR (NOT integra AND primeiro_defeito_id IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "historico_evento" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "historico_evento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entidade" varchar(30) NOT NULL,
	"entidade_id" integer NOT NULL,
	"processo_id" integer,
	"tipo_evento" varchar(40) NOT NULL,
	"descricao" text NOT NULL,
	"comentario" text,
	"campo" varchar(60),
	"valor_anterior" jsonb,
	"valor_novo" jsonb,
	"usuario_id" integer,
	"usuario_nome" varchar(160) NOT NULL,
	"ocorrido_em" timestamp with time zone NOT NULL,
	"registrado_em" timestamp with time zone NOT NULL,
	"origem" varchar(20) DEFAULT 'SISTEMA' NOT NULL,
	"origem_ref" varchar(64),
	"ip" text,
	"user_agent" text,
	"hash_anterior" varchar(64),
	"hash_atual" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "migracao_rejeitada" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "migracao_rejeitada_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"origem" varchar(20) NOT NULL,
	"ref" varchar(200) NOT NULL,
	"motivo" text NOT NULL,
	"payload" jsonb NOT NULL,
	"expurgar_apos" date,
	"criado_em" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pendencia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pendencia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tipo" varchar(40) NOT NULL,
	"descricao" text NOT NULL,
	"processo_id" integer,
	"parecer_id" integer,
	"laudo_id" integer,
	"entidade" varchar(30),
	"entidade_id" integer,
	"responsavel_id" integer,
	"prazo" date,
	"concluida" boolean DEFAULT false NOT NULL,
	"concluida_em" timestamp with time zone,
	"concluida_por" integer,
	"criada_em" timestamp with time zone NOT NULL,
	"chave" varchar(120) NOT NULL,
	CONSTRAINT "ck_pendencia_entidade" CHECK ((entidade IS NULL AND entidade_id IS NULL) OR (entidade IS NOT NULL AND entidade_id IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "stg_planilha_parecer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stg_planilha_parecer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"arquivo" varchar(255) NOT NULL,
	"linha_origem" integer NOT NULL,
	"col_a_data_solicitacao" text,
	"col_b_numero_parecer" text,
	"col_c_nome_servidor" text,
	"col_d_ano" text,
	"col_e_data" text,
	"col_f_laudo_de" text,
	"col_g_unidade" text,
	"col_h_posto_trabalho" text,
	"col_i_uorg" text,
	"col_j_tipo_laudo" text,
	"col_k_numero_processo" text,
	"col_l_matricula" text,
	"col_m_cargo" text,
	"col_n_funcao" text,
	"col_o_laudo_siape" text,
	"col_p_agente_nocivo" text,
	"col_q_tipo_risco" text,
	"col_r_percentual" text,
	"col_s_portaria" text,
	"col_t_fundamentacao" text,
	"col_u_alteracao" text,
	"col_v_recomendacao" text,
	"col_w_reavaliacao" text,
	"col_x_pro_reitor" text,
	"col_Y_sem_cabecalho" text,
	"classificacao" varchar(12),
	"importado_em" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg_trello_acao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stg_trello_acao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_id" varchar(40) NOT NULL,
	"card_id" varchar(40),
	"tipo" varchar(60),
	"data" varchar(40),
	"autor" varchar(160),
	"payload" jsonb NOT NULL,
	CONSTRAINT "stg_trello_acao_action_id_unique" UNIQUE("action_id")
);
--> statement-breakpoint
CREATE TABLE "stg_trello_cartao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stg_trello_cartao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"card_id" varchar(40) NOT NULL,
	"nome" text,
	"descricao" text,
	"lista" text,
	"payload" jsonb NOT NULL,
	"parecer_candidato" varchar(12),
	"laudo_candidato" varchar(24),
	CONSTRAINT "stg_trello_cartao_card_id_unique" UNIQUE("card_id")
);
--> statement-breakpoint
CREATE TABLE "demanda" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "demanda_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"data_chegada" date NOT NULL,
	"canal" varchar(12) NOT NULL,
	"solicitante_nome" varchar(160) NOT NULL,
	"solicitante_servidor_id" integer,
	"solicitante_unidade_uorg_id" integer,
	"assunto" varchar(160) NOT NULL,
	"descricao" text,
	"responsavel_id" integer,
	"prazo" date,
	"estado" varchar(14) DEFAULT 'ABERTA' NOT NULL,
	"desfecho" varchar(16),
	"desfecho_relato" text,
	"desfecho_processo_id" integer,
	"desfecho_setor" varchar(160),
	"desfecho_data" date,
	"encerrada_em" timestamp with time zone,
	"encerrada_por" integer,
	"criada_em" timestamp with time zone NOT NULL,
	"criada_por" integer,
	CONSTRAINT "pk_demanda" PRIMARY KEY("id"),
	CONSTRAINT "ck_demanda_canal" CHECK (canal IN ('EMAIL','PRESENCIAL','TELEFONE','OFICIO','OUTRO')),
	CONSTRAINT "ck_demanda_estado" CHECK (estado IN ('ABERTA','EM_ANDAMENTO','ENCERRADA')),
	CONSTRAINT "ck_demanda_desfecho" CHECK (desfecho IS NULL OR desfecho IN ('RESOLVIDA','VIROU_PROCESSO','ENCAMINHADA','SEM_PROVIDENCIA')),
	CONSTRAINT "ck_demanda_encerrada_tem_desfecho" CHECK ((estado <> 'ENCERRADA' AND desfecho IS NULL) OR (estado = 'ENCERRADA' AND desfecho IS NOT NULL)),
	CONSTRAINT "ck_demanda_desfecho_campos" CHECK ((desfecho IS NULL AND desfecho_relato IS NULL AND desfecho_processo_id IS NULL AND desfecho_setor IS NULL AND desfecho_data IS NULL) OR (     (desfecho <> 'VIROU_PROCESSO' OR desfecho_processo_id IS NOT NULL) AND (desfecho =  'VIROU_PROCESSO' OR desfecho_processo_id IS NULL) AND (desfecho <> 'ENCAMINHADA'      OR (desfecho_setor IS NOT NULL AND desfecho_data IS NOT NULL)) AND (desfecho =  'ENCAMINHADA' OR desfecho_setor IS NULL) AND (desfecho NOT IN ('RESOLVIDA','SEM_PROVIDENCIA')      OR desfecho_relato IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "demanda_encaminhamento" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "demanda_encaminhamento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"demanda_id" integer NOT NULL,
	"data_encaminhamento" date NOT NULL,
	"para_quem" varchar(160) NOT NULL,
	"pedido" text NOT NULL,
	"registrado_por" integer,
	"registrado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_demanda_encaminhamento" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "epi_categoria" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_categoria_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(24) NOT NULL,
	"nome" varchar(80) NOT NULL,
	"referencia_nr6" varchar(12),
	"ordem" smallint DEFAULT 1 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "pk_epi_categoria" PRIMARY KEY("id"),
	CONSTRAINT "uq_epi_categoria" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "epi_entrada_estoque" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_entrada_estoque_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"epi_item_id" integer NOT NULL,
	"tamanho" varchar(20),
	"pregao" varchar(30),
	"item_pregao" varchar(10),
	"empenho" varchar(30),
	"nota_fiscal" varchar(30),
	"fornecedor_nome" varchar(160),
	"fornecedor_cnpj" varchar(14),
	"fornecedor_contato" varchar(120),
	"data_entrada" date NOT NULL,
	"quantidade_empenhada" integer,
	"quantidade_recebida" integer NOT NULL,
	"valor_unitario" numeric(12, 4),
	"lote" varchar(40),
	"numero_ca" varchar(10),
	"validade_ca" date,
	"data_fabricacao" date,
	"observacao" text,
	"ativo" boolean DEFAULT true NOT NULL,
	"motivo_inativacao" text,
	"registrado_por" integer,
	"registrado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_epi_entrada_estoque" PRIMARY KEY("id"),
	CONSTRAINT "ck_entrada_qtd" CHECK (quantidade_recebida > 0),
	CONSTRAINT "ck_entrada_empenho" CHECK (quantidade_empenhada IS NULL OR quantidade_empenhada >= quantidade_recebida),
	CONSTRAINT "ck_entrada_inativa" CHECK (ativo OR motivo_inativacao IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "epi_ficha_registro" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_ficha_registro_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"servidor_id" integer NOT NULL,
	"epi_item_id" integer NOT NULL,
	"requisicao_item_id" integer,
	"entrada_id" integer,
	"tipo" varchar(14) NOT NULL,
	"quantidade" smallint NOT NULL,
	"data_evento" date NOT NULL,
	"nome_epi_snapshot" varchar(180) NOT NULL,
	"categoria_snapshot" varchar(80) NOT NULL,
	"numero_ca_snapshot" varchar(10),
	"validade_ca_snapshot" date,
	"fabricante_snapshot" varchar(120),
	"lote_snapshot" varchar(40),
	"tamanho_snapshot" varchar(20),
	"nome_servidor_snapshot" varchar(160) NOT NULL,
	"siape_snapshot" varchar(7) NOT NULL,
	"cargo_snapshot" varchar(120),
	"unidade_snapshot" varchar(160),
	"posto_snapshot" varchar(200),
	"contexto_congelado" jsonb,
	"previsao_troca" date,
	"entregue_por" integer NOT NULL,
	"comprovante_anexo_id" integer,
	"recebimento_confirmado_em" timestamp with time zone,
	"motivo" text,
	"registro_estornado_id" integer,
	"evento_id" integer,
	"registrado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_epi_ficha_registro" PRIMARY KEY("id"),
	CONSTRAINT "ck_ficha_tipo" CHECK (tipo IN ('ENTREGA','DEVOLUCAO','SUBSTITUICAO','DESCARTE','ESTORNO')),
	CONSTRAINT "ck_ficha_quantidade" CHECK (quantidade > 0),
	CONSTRAINT "ck_ficha_estorno" CHECK (tipo <> 'ESTORNO' OR (registro_estornado_id IS NOT NULL AND motivo IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "epi_item" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(180) NOT NULL,
	"descricao" text,
	"categoria_id" integer NOT NULL,
	"codigo_ecampus" varchar(20),
	"codigo_catmat" varchar(20),
	"fabricante" varchar(120),
	"marca" varchar(80),
	"modelo" varchar(80),
	"normas" text,
	"exige_ca" boolean DEFAULT true NOT NULL,
	"numero_ca" varchar(10),
	"validade_ca" date,
	"unidade_medida" varchar(20) DEFAULT 'UNIDADE' NOT NULL,
	"tamanhos" text,
	"vida_util_meses" smallint,
	"quantidade_padrao" smallint DEFAULT 1 NOT NULL,
	"quantidade_maxima" smallint,
	"periodo_maximo_meses" smallint,
	"exige_justificativa" boolean DEFAULT false NOT NULL,
	"exige_treinamento" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp with time zone NOT NULL,
	"atualizado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_epi_item" PRIMARY KEY("id"),
	CONSTRAINT "uq_epi_item" UNIQUE("nome","modelo"),
	CONSTRAINT "ck_epi_qtd_padrao" CHECK (quantidade_padrao > 0),
	CONSTRAINT "ck_epi_qtd_maxima" CHECK (quantidade_maxima IS NULL OR quantidade_maxima >= quantidade_padrao),
	CONSTRAINT "ck_epi_janela" CHECK ((quantidade_maxima IS NULL) = (periodo_maximo_meses IS NULL)),
	CONSTRAINT "ck_epi_ca_obrigatorio" CHECK (NOT exige_ca OR numero_ca IS NOT NULL),
	CONSTRAINT "ck_epi_vida_util" CHECK (vida_util_meses IS NULL OR vida_util_meses > 0)
);
--> statement-breakpoint
CREATE TABLE "epi_motivo_recusa" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_motivo_recusa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(32) NOT NULL,
	"rotulo" varchar(80) NOT NULL,
	"texto" text NOT NULL,
	"base_normativa" varchar(120),
	"exige_complemento" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"dispositivo_conferido_em" date,
	CONSTRAINT "pk_epi_motivo_recusa" PRIMARY KEY("id"),
	CONSTRAINT "uq_epi_motivo_recusa" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "epi_movimento_estoque" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_movimento_estoque_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entrada_id" integer NOT NULL,
	"tipo" varchar(12) NOT NULL,
	"quantidade" integer NOT NULL,
	"requisicao_item_id" integer,
	"ficha_registro_id" integer,
	"motivo" text,
	"ocorrido_em" timestamp with time zone NOT NULL,
	"registrado_por" integer,
	CONSTRAINT "pk_epi_movimento_estoque" PRIMARY KEY("id"),
	CONSTRAINT "ck_mov_tipo" CHECK (tipo IN ('ENTRADA','SAIDA','DEVOLUCAO','DESCARTE','AJUSTE')),
	CONSTRAINT "ck_mov_quantidade" CHECK (quantidade <> 0),
	CONSTRAINT "ck_mov_sinal" CHECK ((tipo IN ('ENTRADA','DEVOLUCAO') AND quantidade > 0) OR (tipo IN ('SAIDA','DESCARTE') AND quantidade < 0) OR tipo = 'AJUSTE'),
	CONSTRAINT "ck_mov_motivo" CHECK (tipo NOT IN ('AJUSTE','DESCARTE') OR motivo IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "epi_requisicao" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_requisicao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"protocolo" varchar(16),
	"numero" integer,
	"ano" integer,
	"servidor_id" integer NOT NULL,
	"solicitado_por_id" integer NOT NULL,
	"chefia_servidor_id" integer,
	"unidade_uorg_id" integer,
	"campus_id" integer,
	"posto_trabalho_id" integer,
	"cargo_snapshot" varchar(120),
	"funcao_snapshot" varchar(120),
	"finalidade" varchar(20) DEFAULT 'ROTINA' NOT NULL,
	"descricao_atividade" text,
	"riscos_declarados" text,
	"urgencia" varchar(10) DEFAULT 'NORMAL' NOT NULL,
	"justificativa_urgencia" text,
	"estado" varchar(16) DEFAULT 'RASCUNHO' NOT NULL,
	"estado_anterior" varchar(16),
	"entrou_no_estado_em" timestamp with time zone NOT NULL,
	"analisado_por" integer,
	"analisado_em" timestamp with time zone,
	"parecer_analise" text,
	"motivo_recusa_id" integer,
	"complemento_recusa" text,
	"motivo_cancelamento" text,
	"enviada_em" timestamp with time zone,
	"criado_em" timestamp with time zone NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "pk_epi_requisicao" PRIMARY KEY("id"),
	CONSTRAINT "uq_req_protocolo" UNIQUE("protocolo"),
	CONSTRAINT "uq_req_numero" UNIQUE("ano","numero"),
	CONSTRAINT "ck_req_estado" CHECK (estado IN ('RASCUNHO','ENVIADA','EM_ANALISE','ANALISADA','EM_ATENDIMENTO','ATENDIDA','INDEFERIDA','CANCELADA')),
	CONSTRAINT "ck_req_urgencia" CHECK (urgencia IN ('NORMAL','URGENTE')),
	CONSTRAINT "ck_req_urgencia_justificada" CHECK (urgencia <> 'URGENTE' OR justificativa_urgencia IS NOT NULL),
	CONSTRAINT "ck_req_finalidade" CHECK (finalidade IN ('PRIMEIRA_ENTREGA','ROTINA','SUBSTITUICAO','DANO','PERDA')),
	CONSTRAINT "ck_req_protocolo" CHECK ((estado = 'RASCUNHO') = (protocolo IS NULL)),
	CONSTRAINT "ck_req_numero" CHECK ((protocolo IS NULL) = (numero IS NULL) AND (protocolo IS NULL) = (ano IS NULL)),
	CONSTRAINT "ck_req_indeferida" CHECK (estado <> 'INDEFERIDA' OR motivo_recusa_id IS NOT NULL),
	CONSTRAINT "ck_req_cancelada" CHECK (estado <> 'CANCELADA' OR motivo_cancelamento IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "epi_requisicao_item" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "epi_requisicao_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requisicao_id" integer NOT NULL,
	"epi_item_id" integer NOT NULL,
	"tamanho" varchar(20),
	"quantidade_solicitada" smallint NOT NULL,
	"quantidade_aprovada" smallint,
	"quantidade_reservada" smallint DEFAULT 0 NOT NULL,
	"quantidade_entregue" smallint DEFAULT 0 NOT NULL,
	"entrada_id" integer,
	"justificativa" text,
	"excedeu_maximo" boolean DEFAULT false NOT NULL,
	"autorizado_por" integer,
	"estado" varchar(14) DEFAULT 'SOLICITADO' NOT NULL,
	"motivo_recusa_id" integer,
	"complemento_recusa" text,
	"texto_recusa_snapshot" text,
	"decidido_por" integer,
	"decidido_em" timestamp with time zone,
	CONSTRAINT "pk_epi_requisicao_item" PRIMARY KEY("id"),
	CONSTRAINT "uq_req_item" UNIQUE("requisicao_id","epi_item_id","tamanho"),
	CONSTRAINT "ck_req_item_estado" CHECK (estado IN ('SOLICITADO','APROVADO','RESERVADO','SEM_ESTOQUE','ENTREGUE','RECUSADO','CANCELADO')),
	CONSTRAINT "ck_item_solicitada" CHECK (quantidade_solicitada > 0),
	CONSTRAINT "ck_item_aprovada" CHECK (quantidade_aprovada IS NULL OR (quantidade_aprovada >= 0 AND quantidade_aprovada <= quantidade_solicitada)),
	CONSTRAINT "ck_item_entregue" CHECK (quantidade_entregue <= COALESCE(quantidade_aprovada, quantidade_solicitada)),
	CONSTRAINT "ck_item_reservada" CHECK (quantidade_reservada <= COALESCE(quantidade_aprovada, quantidade_solicitada)),
	CONSTRAINT "ck_item_recusado" CHECK (estado <> 'RECUSADO' OR (motivo_recusa_id IS NOT NULL AND texto_recusa_snapshot IS NOT NULL)),
	CONSTRAINT "ck_item_excecao" CHECK (NOT excedeu_maximo OR (autorizado_por IS NOT NULL AND justificativa IS NOT NULL)),
	CONSTRAINT "ck_item_lote" CHECK (estado <> 'RESERVADO' OR entrada_id IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "epi_requisicao_sequencia" (
	"ano" integer NOT NULL,
	"ultimo_numero" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pk_epi_requisicao_sequencia" PRIMARY KEY("ano")
);
--> statement-breakpoint
CREATE TABLE "assinatura_instrutor" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "assinatura_instrutor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"servidor_id" integer,
	"nome" varchar(160) NOT NULL,
	"titulo" varchar(120),
	"conselho" varchar(8),
	"registro_conselho" varchar(30),
	"organizacao" varchar(160),
	"externo" boolean DEFAULT false NOT NULL,
	"imagem_anexo_id" integer,
	"vigencia_inicio" date NOT NULL,
	"vigencia_fim" date,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "pk_assinatura_instrutor" PRIMARY KEY("id"),
	CONSTRAINT "ck_assinatura_vinculo" CHECK (externo OR servidor_id IS NOT NULL),
	CONSTRAINT "ck_assinatura_periodo" CHECK (vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);
--> statement-breakpoint
CREATE TABLE "certificado" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "certificado_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"inscricao_id" integer NOT NULL,
	"numero" integer NOT NULL,
	"ano" integer NOT NULL,
	"chave_validacao" varchar(24) NOT NULL,
	"situacao" varchar(12) DEFAULT 'EMITIDO' NOT NULL,
	"data_emissao" date NOT NULL,
	"data_base_vencimento" date NOT NULL,
	"data_vencimento" date,
	"validade_meses_congelada" integer NOT NULL,
	"contexto_congelado" jsonb NOT NULL,
	"modelo_id" integer,
	"modelo_arquivo" varchar(120) NOT NULL,
	"modelo_sha256" varchar(64),
	"hash_conteudo" varchar(64),
	"arquivo_docx" text,
	"arquivo_pdf_anexo_id" integer,
	"servidor_id" integer,
	"campus_id" integer,
	"treinamento_id" integer NOT NULL,
	"participante_id" integer NOT NULL,
	"emitido_por" integer,
	"emitido_em" timestamp with time zone NOT NULL,
	"anulado_em" timestamp with time zone,
	"anulado_por" integer,
	"motivo_anulacao" text,
	"substituido_por_id" integer,
	CONSTRAINT "pk_certificado" PRIMARY KEY("id"),
	CONSTRAINT "uq_certificado" UNIQUE("numero","ano"),
	CONSTRAINT "uq_certificado_chave" UNIQUE("chave_validacao"),
	CONSTRAINT "ck_certificado_situacao" CHECK (situacao IN ('EMITIDO','ANULADO')),
	CONSTRAINT "ck_certificado_anulado" CHECK (situacao <> 'ANULADO' OR motivo_anulacao IS NOT NULL),
	CONSTRAINT "ck_certificado_vencimento" CHECK ((validade_meses_congelada = 0 AND data_vencimento IS NULL) OR (validade_meses_congelada > 0 AND data_vencimento IS NOT NULL)),
	CONSTRAINT "ck_certificado_validade" CHECK (validade_meses_congelada >= 0),
	CONSTRAINT "ck_certificado_ano" CHECK (EXTRACT(YEAR FROM data_emissao) = ano),
	CONSTRAINT "ck_certificado_substituto" CHECK (substituido_por_id IS NULL OR substituido_por_id <> id),
	CONSTRAINT "ck_certificado_chave" CHECK (chave_validacao ~ '^(?:CSSO-\d{4}-[23456789ABCDEFGHJKMNPQRSTVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTVWXYZ])$')
);
--> statement-breakpoint
CREATE TABLE "certificado_modelo" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "certificado_modelo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"treinamento_id" integer,
	"nome" varchar(120) NOT NULL,
	"arquivo" varchar(120) NOT NULL,
	"arquivo_sha256" varchar(64),
	"orientacao" varchar(10) DEFAULT 'PAISAGEM' NOT NULL,
	"versao" integer DEFAULT 1 NOT NULL,
	"vigente" boolean DEFAULT true NOT NULL,
	"observacao" text,
	"criado_por" integer,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_certificado_modelo" PRIMARY KEY("id"),
	CONSTRAINT "uq_certificado_modelo" UNIQUE("treinamento_id","nome","versao"),
	CONSTRAINT "ck_modelo_orientacao" CHECK (orientacao IN ('PAISAGEM','RETRATO')),
	CONSTRAINT "ck_modelo_versao" CHECK (versao >= 1)
);
--> statement-breakpoint
CREATE TABLE "certificado_modelo_tag" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "certificado_modelo_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"modelo_id" integer NOT NULL,
	"marcador" varchar(60) NOT NULL,
	"campo" varchar(60) NOT NULL,
	"ordem" smallint DEFAULT 1 NOT NULL,
	"obrigatorio" boolean DEFAULT true NOT NULL,
	CONSTRAINT "pk_certificado_modelo_tag" PRIMARY KEY("id"),
	CONSTRAINT "uq_modelo_tag" UNIQUE("modelo_id","marcador"),
	CONSTRAINT "ck_modelo_tag_marcador" CHECK (marcador ~ '^(?:[A-Za-z_][A-Za-z0-9_]*)$')
);
--> statement-breakpoint
CREATE TABLE "certificado_sequencia" (
	"ano" integer NOT NULL,
	"ultimo_numero" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pk_certificado_sequencia" PRIMARY KEY("ano")
);
--> statement-breakpoint
CREATE TABLE "inscricao" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "inscricao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"turma_id" integer NOT NULL,
	"participante_id" integer NOT NULL,
	"situacao" varchar(24) DEFAULT 'INSCRITA' NOT NULL,
	"origem" varchar(12) DEFAULT 'INTERNA' NOT NULL,
	"confirmacao_token_hash" varchar(64),
	"confirmacao_expira_em" timestamp with time zone,
	"email_confirmado_em" timestamp with time zone,
	"ip_inscricao" text,
	"inscrito_em" timestamp with time zone NOT NULL,
	"inscrito_por" integer,
	"confirmada_em" timestamp with time zone,
	"confirmada_por" integer,
	"frequencia_percentual" numeric(5, 2),
	"nota_final" numeric(5, 2),
	"observacao" text,
	"motivo_cancelamento" text,
	CONSTRAINT "pk_inscricao" PRIMARY KEY("id"),
	CONSTRAINT "uq_inscricao" UNIQUE("turma_id","participante_id"),
	CONSTRAINT "uq_inscricao_token" UNIQUE("confirmacao_token_hash"),
	CONSTRAINT "ck_inscricao_situacao" CHECK (situacao IN ('AGUARDANDO_EMAIL','INSCRITA','CONFIRMADA','PRESENTE','AUSENTE','APROVADO','REPROVADO','CANCELADA')),
	CONSTRAINT "ck_inscricao_origem" CHECK (origem IN ('INTERNA','PUBLICA')),
	CONSTRAINT "ck_inscricao_nota" CHECK (nota_final IS NULL OR (nota_final >= 0 AND nota_final <= 10)),
	CONSTRAINT "ck_inscricao_frequencia" CHECK (frequencia_percentual IS NULL OR (frequencia_percentual >= 0 AND frequencia_percentual <= 100)),
	CONSTRAINT "ck_inscricao_cancelada" CHECK (situacao <> 'CANCELADA' OR motivo_cancelamento IS NOT NULL),
	CONSTRAINT "ck_inscricao_email_confirmado" CHECK (origem = 'INTERNA' OR situacao = 'AGUARDANDO_EMAIL' OR email_confirmado_em IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "participante" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "participante_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"servidor_id" integer,
	"nome" varchar(160),
	"identificador_publico" varchar(14) NOT NULL,
	"vinculo" varchar(16) NOT NULL,
	"organizacao" varchar(160),
	"matricula_externa" varchar(30),
	"email_principal_id" integer,
	"mesclado_em_id" integer,
	"expurgar_apos" date,
	"expurgado_em" timestamp with time zone,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_participante" PRIMARY KEY("id"),
	CONSTRAINT "uq_participante_servidor" UNIQUE("servidor_id"),
	CONSTRAINT "uq_participante_identificador" UNIQUE("identificador_publico"),
	CONSTRAINT "ck_participante_nome" CHECK ((servidor_id IS NOT NULL AND nome IS NULL) OR (servidor_id IS NULL AND nome IS NOT NULL) OR expurgado_em IS NOT NULL),
	CONSTRAINT "ck_participante_vinculo" CHECK (vinculo IN ('SERVIDOR','TERCEIRIZADO','DISCENTE','VISITANTE','OUTRO')),
	CONSTRAINT "ck_participante_servidor" CHECK (vinculo <> 'SERVIDOR' OR servidor_id IS NOT NULL),
	CONSTRAINT "ck_participante_identificador" CHECK (identificador_publico ~ '^(?:PTC-[23456789ABCDEFGHJKMNPQRSTVWXYZ]{8})$')
);
--> statement-breakpoint
CREATE TABLE "participante_email" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "participante_email_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"participante_id" integer NOT NULL,
	"email" varchar(160) NOT NULL,
	"email_normalizado" varchar(160) NOT NULL,
	"confirmado_em" timestamp with time zone,
	"origem" varchar(20) DEFAULT 'CADASTRO' NOT NULL,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_participante_email" PRIMARY KEY("id"),
	CONSTRAINT "uq_participante_email" UNIQUE("participante_id","email_normalizado"),
	CONSTRAINT "ck_participante_email_origem" CHECK (origem IN ('CADASTRO','INSCRICAO_PUBLICA','SERVIDOR','MESCLAGEM'))
);
--> statement-breakpoint
CREATE TABLE "treinamento" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "treinamento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(30) NOT NULL,
	"nome" varchar(160) NOT NULL,
	"carga_horaria_horas" numeric(5, 1) NOT NULL,
	"conteudo_programatico" text,
	"validade_meses" integer DEFAULT 0 NOT NULL,
	"norma_referencia" varchar(120),
	"obrigatorio" boolean DEFAULT false NOT NULL,
	"modelo_vigente_id" integer,
	"instrutor_padrao_id" integer,
	"ativo" boolean DEFAULT true NOT NULL,
	CONSTRAINT "pk_treinamento" PRIMARY KEY("id"),
	CONSTRAINT "uq_treinamento_codigo" UNIQUE("codigo"),
	CONSTRAINT "uq_treinamento_nome" UNIQUE("nome"),
	CONSTRAINT "ck_treinamento_validade" CHECK (validade_meses >= 0),
	CONSTRAINT "ck_treinamento_carga" CHECK (carga_horaria_horas > 0),
	CONSTRAINT "ck_treinamento_codigo" CHECK (codigo ~ '^(?:[A-Z0-9][A-Z0-9._-]*)$')
);
--> statement-breakpoint
CREATE TABLE "turma" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "turma_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"treinamento_id" integer NOT NULL,
	"numero" integer NOT NULL,
	"ano" integer NOT NULL,
	"codigo" varchar(20) NOT NULL,
	"data_inicio" date NOT NULL,
	"data_fim" date NOT NULL,
	"data_base_vencimento" date,
	"carga_horaria_horas" numeric(5, 1),
	"local" varchar(160),
	"campus_id" integer,
	"unidade_promotora_id" integer,
	"vagas" integer,
	"inscricao_aberta_ate" date,
	"inscricao_publica" boolean DEFAULT false NOT NULL,
	"inscricao_token_hash" varchar(64),
	"inscricao_token_expira_em" timestamp with time zone,
	"nota_minima_aprovacao" numeric(5, 2),
	"frequencia_minima_percentual" numeric(5, 2) DEFAULT '75' NOT NULL,
	"situacao" varchar(20) DEFAULT 'PLANEJADA' NOT NULL,
	"motivo_cancelamento" text,
	"observacoes" text,
	"concluida_em" timestamp with time zone,
	"criado_por" integer,
	"criado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_turma" PRIMARY KEY("id"),
	CONSTRAINT "uq_turma" UNIQUE("numero","ano"),
	CONSTRAINT "uq_turma_codigo" UNIQUE("codigo"),
	CONSTRAINT "uq_turma_token" UNIQUE("inscricao_token_hash"),
	CONSTRAINT "ck_turma_periodo" CHECK (data_fim >= data_inicio),
	CONSTRAINT "ck_turma_situacao" CHECK (situacao IN ('PLANEJADA','INSCRICOES_ABERTAS','EM_ANDAMENTO','CONCLUIDA','CANCELADA')),
	CONSTRAINT "ck_turma_cancelada" CHECK (situacao <> 'CANCELADA' OR motivo_cancelamento IS NOT NULL),
	CONSTRAINT "ck_turma_vagas" CHECK (vagas IS NULL OR vagas > 0),
	CONSTRAINT "ck_turma_carga" CHECK (carga_horaria_horas IS NULL OR carga_horaria_horas > 0),
	CONSTRAINT "ck_turma_inscricao_publica" CHECK (NOT inscricao_publica OR inscricao_aberta_ate IS NOT NULL),
	CONSTRAINT "ck_turma_nota_minima" CHECK (nota_minima_aprovacao IS NULL OR (nota_minima_aprovacao >= 0 AND nota_minima_aprovacao <= 10)),
	CONSTRAINT "ck_turma_frequencia_minima" CHECK (frequencia_minima_percentual >= 0 AND frequencia_minima_percentual <= 100),
	CONSTRAINT "ck_turma_ano" CHECK (EXTRACT(YEAR FROM data_inicio) = ano)
);
--> statement-breakpoint
CREATE TABLE "turma_instrutor" (
	"turma_id" integer NOT NULL,
	"assinatura_instrutor_id" integer NOT NULL,
	"ordem" smallint DEFAULT 1 NOT NULL,
	"assina_certificado" boolean DEFAULT true NOT NULL,
	CONSTRAINT "pk_turma_instrutor" PRIMARY KEY("turma_id","assinatura_instrutor_id")
);
--> statement-breakpoint
CREATE TABLE "turma_presenca" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "turma_presenca_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"inscricao_id" integer NOT NULL,
	"data" date NOT NULL,
	"horas" numeric(4, 1) DEFAULT '0' NOT NULL,
	"presente" boolean DEFAULT true NOT NULL,
	"justificativa" text,
	"registrado_por" integer,
	"registrado_em" timestamp with time zone NOT NULL,
	CONSTRAINT "pk_turma_presenca" PRIMARY KEY("id"),
	CONSTRAINT "uq_turma_presenca_dia" UNIQUE("inscricao_id","data"),
	CONSTRAINT "ck_turma_presenca_horas" CHECK (horas >= 0),
	CONSTRAINT "ck_turma_presenca_coerente" CHECK (presente OR horas = 0)
);
--> statement-breakpoint
CREATE TABLE "turma_sequencia" (
	"ano" integer NOT NULL,
	"ultimo_numero" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pk_turma_sequencia" PRIMARY KEY("ano")
);
--> statement-breakpoint
ALTER TABLE "agente_nocivo" ADD CONSTRAINT "agente_nocivo_tipo_risco_id_tipo_risco_id_fk" FOREIGN KEY ("tipo_risco_id") REFERENCES "public"."tipo_risco"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agente_nocivo" ADD CONSTRAINT "agente_nocivo_fundamentacao_id_fundamentacao_legal_id_fk" FOREIGN KEY ("fundamentacao_id") REFERENCES "public"."fundamentacao_legal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agente_nocivo" ADD CONSTRAINT "agente_nocivo_percentual_sugerido_id_percentual_aplicavel_id_fk" FOREIGN KEY ("percentual_sugerido_id") REFERENCES "public"."percentual_aplicavel"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agente_nocivo" ADD CONSTRAINT "agente_nocivo_agente_canonico_id_agente_nocivo_id_fk" FOREIGN KEY ("agente_canonico_id") REFERENCES "public"."agente_nocivo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_modelo" ADD CONSTRAINT "checklist_modelo_tipo_processo_id_tipo_processo_id_fk" FOREIGN KEY ("tipo_processo_id") REFERENCES "public"."tipo_processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fundamentacao_legal" ADD CONSTRAINT "fundamentacao_legal_tipo_risco_id_tipo_risco_id_fk" FOREIGN KEY ("tipo_risco_id") REFERENCES "public"."tipo_risco"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "percentual_aplicavel" ADD CONSTRAINT "percentual_aplicavel_tipo_adicional_id_tipo_adicional_id_fk" FOREIGN KEY ("tipo_adicional_id") REFERENCES "public"."tipo_adicional"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lotacao_posto" ADD CONSTRAINT "fk_lotacao_posto_lotacao" FOREIGN KEY ("lotacao_id") REFERENCES "public"."servidor_lotacao"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lotacao_posto" ADD CONSTRAINT "fk_lotacao_posto_posto" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portaria_localizacao" ADD CONSTRAINT "portaria_localizacao_unidade_emissora_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_emissora_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portaria_servidor" ADD CONSTRAINT "portaria_servidor_portaria_id_portaria_localizacao_id_fk" FOREIGN KEY ("portaria_id") REFERENCES "public"."portaria_localizacao"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portaria_servidor" ADD CONSTRAINT "portaria_servidor_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portaria_servidor" ADD CONSTRAINT "portaria_servidor_posto_trabalho_id_posto_trabalho_id_fk" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posto_trabalho" ADD CONSTRAINT "posto_trabalho_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor" ADD CONSTRAINT "servidor_cargo_id_cargo_id_fk" FOREIGN KEY ("cargo_id") REFERENCES "public"."cargo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor" ADD CONSTRAINT "servidor_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor" ADD CONSTRAINT "fk_servidor_uorg" FOREIGN KEY ("uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor_lotacao" ADD CONSTRAINT "servidor_lotacao_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor_lotacao" ADD CONSTRAINT "servidor_lotacao_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor_lotacao" ADD CONSTRAINT "servidor_lotacao_cargo_id_cargo_id_fk" FOREIGN KEY ("cargo_id") REFERENCES "public"."cargo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor_lotacao" ADD CONSTRAINT "servidor_lotacao_registrado_por_usuario_id_fk" FOREIGN KEY ("registrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servidor_lotacao" ADD CONSTRAINT "fk_lotacao_uorg" FOREIGN KEY ("uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "unidade_uorg" ADD CONSTRAINT "unidade_uorg_unidade_pai_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_pai_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "unidade_uorg" ADD CONSTRAINT "unidade_uorg_campus_id_campus_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acesso_dado_sensivel" ADD CONSTRAINT "acesso_dado_sensivel_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acesso_dado_sensivel" ADD CONSTRAINT "acesso_dado_sensivel_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acesso_dado_sensivel" ADD CONSTRAINT "acesso_dado_sensivel_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atribuicao" ADD CONSTRAINT "atribuicao_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atribuicao" ADD CONSTRAINT "atribuicao_perfil_id_perfil_id_fk" FOREIGN KEY ("perfil_id") REFERENCES "public"."perfil"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atribuicao" ADD CONSTRAINT "atribuicao_campus_id_campus_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "atribuicao" ADD CONSTRAINT "atribuicao_concedido_por_usuario_id_fk" FOREIGN KEY ("concedido_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "perfil_permissao" ADD CONSTRAINT "perfil_permissao_perfil_id_perfil_id_fk" FOREIGN KEY ("perfil_id") REFERENCES "public"."perfil"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "perfil_permissao" ADD CONSTRAINT "perfil_permissao_permissao_id_permissao_id_fk" FOREIGN KEY ("permissao_id") REFERENCES "public"."permissao"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profissional_habilitado" ADD CONSTRAINT "profissional_habilitado_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profissional_habilitado" ADD CONSTRAINT "profissional_habilitado_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profissional_habilitado" ADD CONSTRAINT "profissional_habilitado_atestado_por_usuario_id_fk" FOREIGN KEY ("atestado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessao" ADD CONSTRAINT "sessao_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuario" ADD CONSTRAINT "usuario_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adicional_vigencia" ADD CONSTRAINT "adicional_vigencia_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adicional_vigencia" ADD CONSTRAINT "adicional_vigencia_parecer_id_parecer_tecnico_id_fk" FOREIGN KEY ("parecer_id") REFERENCES "public"."parecer_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adicional_vigencia" ADD CONSTRAINT "adicional_vigencia_tipo_adicional_id_tipo_adicional_id_fk" FOREIGN KEY ("tipo_adicional_id") REFERENCES "public"."tipo_adicional"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adicional_vigencia" ADD CONSTRAINT "adicional_vigencia_percentual_id_percentual_aplicavel_id_fk" FOREIGN KEY ("percentual_id") REFERENCES "public"."percentual_aplicavel"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exposicao" ADD CONSTRAINT "exposicao_parecer_id_parecer_tecnico_id_fk" FOREIGN KEY ("parecer_id") REFERENCES "public"."parecer_tecnico"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exposicao" ADD CONSTRAINT "exposicao_agente_nocivo_id_agente_nocivo_id_fk" FOREIGN KEY ("agente_nocivo_id") REFERENCES "public"."agente_nocivo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exposicao" ADD CONSTRAINT "exposicao_percentual_id_percentual_aplicavel_id_fk" FOREIGN KEY ("percentual_id") REFERENCES "public"."percentual_aplicavel"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exposicao" ADD CONSTRAINT "exposicao_fundamentacao_id_fundamentacao_legal_id_fk" FOREIGN KEY ("fundamentacao_id") REFERENCES "public"."fundamentacao_legal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exposicao" ADD CONSTRAINT "exposicao_posto_trabalho_id_posto_trabalho_id_fk" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_posto" ADD CONSTRAINT "laudo_posto_laudo_id_laudo_tecnico_id_fk" FOREIGN KEY ("laudo_id") REFERENCES "public"."laudo_tecnico"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_posto" ADD CONSTRAINT "laudo_posto_posto_trabalho_id_posto_trabalho_id_fk" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_tecnico" ADD CONSTRAINT "laudo_tecnico_tipo_adicional_id_tipo_adicional_id_fk" FOREIGN KEY ("tipo_adicional_id") REFERENCES "public"."tipo_adicional"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_tecnico" ADD CONSTRAINT "laudo_tecnico_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_tecnico" ADD CONSTRAINT "laudo_tecnico_subscritor_id_profissional_habilitado_id_fk" FOREIGN KEY ("subscritor_id") REFERENCES "public"."profissional_habilitado"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_tecnico" ADD CONSTRAINT "laudo_tecnico_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laudo_tecnico" ADD CONSTRAINT "laudo_tecnico_substituido_por_id_laudo_tecnico_id_fk" FOREIGN KEY ("substituido_por_id") REFERENCES "public"."laudo_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_posto" ADD CONSTRAINT "parecer_posto_parecer_id_parecer_tecnico_id_fk" FOREIGN KEY ("parecer_id") REFERENCES "public"."parecer_tecnico"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_posto" ADD CONSTRAINT "parecer_posto_posto_trabalho_id_posto_trabalho_id_fk" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_laudo_id_laudo_tecnico_id_fk" FOREIGN KEY ("laudo_id") REFERENCES "public"."laudo_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_tipo_adicional_id_tipo_adicional_id_fk" FOREIGN KEY ("tipo_adicional_id") REFERENCES "public"."tipo_adicional"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_tipo_movimento_id_tipo_movimento_id_fk" FOREIGN KEY ("tipo_movimento_id") REFERENCES "public"."tipo_movimento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_portaria_id_portaria_localizacao_id_fk" FOREIGN KEY ("portaria_id") REFERENCES "public"."portaria_localizacao"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_destinatario_id_autoridade_destinataria_id_fk" FOREIGN KEY ("destinatario_id") REFERENCES "public"."autoridade_destinataria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_signatario_id_profissional_habilitado_id_fk" FOREIGN KEY ("signatario_id") REFERENCES "public"."profissional_habilitado"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_setor_emissor_id_setor_emissor_id_fk" FOREIGN KEY ("setor_emissor_id") REFERENCES "public"."setor_emissor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_campus_id_campus_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_parecer_anterior_id_parecer_tecnico_id_fk" FOREIGN KEY ("parecer_anterior_id") REFERENCES "public"."parecer_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_tipo_marco_id_tipo_marco_inicial_id_fk" FOREIGN KEY ("tipo_marco_id") REFERENCES "public"."tipo_marco_inicial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_criado_por_usuario_id_fk" FOREIGN KEY ("criado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "parecer_tecnico_emitido_por_usuario_id_fk" FOREIGN KEY ("emitido_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parecer_tecnico" ADD CONSTRAINT "fk_parecer_uorg" FOREIGN KEY ("uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processo" ADD CONSTRAINT "processo_tipo_processo_id_tipo_processo_id_fk" FOREIGN KEY ("tipo_processo_id") REFERENCES "public"."tipo_processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processo" ADD CONSTRAINT "processo_etapa_id_fluxo_etapa_id_fk" FOREIGN KEY ("etapa_id") REFERENCES "public"."fluxo_etapa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processo" ADD CONSTRAINT "processo_servidor_id_servidor_id_fk" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processo" ADD CONSTRAINT "processo_unidade_uorg_id_unidade_uorg_id_fk" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processo" ADD CONSTRAINT "processo_responsavel_id_usuario_id_fk" FOREIGN KEY ("responsavel_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anexo" ADD CONSTRAINT "anexo_enviado_por_usuario_id_fk" FOREIGN KEY ("enviado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist" ADD CONSTRAINT "checklist_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_item" ADD CONSTRAINT "checklist_item_checklist_id_checklist_id_fk" FOREIGN KEY ("checklist_id") REFERENCES "public"."checklist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_item" ADD CONSTRAINT "checklist_item_concluido_por_usuario_id_fk" FOREIGN KEY ("concluido_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conferencia_cadeia" ADD CONSTRAINT "conferencia_cadeia_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "historico_evento" ADD CONSTRAINT "historico_evento_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "historico_evento" ADD CONSTRAINT "historico_evento_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pendencia" ADD CONSTRAINT "pendencia_processo_id_processo_id_fk" FOREIGN KEY ("processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pendencia" ADD CONSTRAINT "pendencia_parecer_id_parecer_tecnico_id_fk" FOREIGN KEY ("parecer_id") REFERENCES "public"."parecer_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pendencia" ADD CONSTRAINT "pendencia_laudo_id_laudo_tecnico_id_fk" FOREIGN KEY ("laudo_id") REFERENCES "public"."laudo_tecnico"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pendencia" ADD CONSTRAINT "pendencia_responsavel_id_usuario_id_fk" FOREIGN KEY ("responsavel_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pendencia" ADD CONSTRAINT "pendencia_concluida_por_usuario_id_fk" FOREIGN KEY ("concluida_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_servidor" FOREIGN KEY ("solicitante_servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_unidade" FOREIGN KEY ("solicitante_unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_responsavel" FOREIGN KEY ("responsavel_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_processo" FOREIGN KEY ("desfecho_processo_id") REFERENCES "public"."processo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_encerrada_por" FOREIGN KEY ("encerrada_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda" ADD CONSTRAINT "fk_demanda_criada_por" FOREIGN KEY ("criada_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda_encaminhamento" ADD CONSTRAINT "fk_encaminhamento_demanda" FOREIGN KEY ("demanda_id") REFERENCES "public"."demanda"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demanda_encaminhamento" ADD CONSTRAINT "fk_encaminhamento_autor" FOREIGN KEY ("registrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_entrada_estoque" ADD CONSTRAINT "fk_epi_entrada_item" FOREIGN KEY ("epi_item_id") REFERENCES "public"."epi_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_entrada_estoque" ADD CONSTRAINT "fk_epi_entrada_registrado_por" FOREIGN KEY ("registrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_servidor" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_item" FOREIGN KEY ("epi_item_id") REFERENCES "public"."epi_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_requisicao_item" FOREIGN KEY ("requisicao_item_id") REFERENCES "public"."epi_requisicao_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_entrada" FOREIGN KEY ("entrada_id") REFERENCES "public"."epi_entrada_estoque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_entregue_por" FOREIGN KEY ("entregue_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_comprovante" FOREIGN KEY ("comprovante_anexo_id") REFERENCES "public"."anexo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_estornado" FOREIGN KEY ("registro_estornado_id") REFERENCES "public"."epi_ficha_registro"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_ficha_registro" ADD CONSTRAINT "fk_epi_ficha_evento" FOREIGN KEY ("evento_id") REFERENCES "public"."historico_evento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_item" ADD CONSTRAINT "fk_epi_item_categoria" FOREIGN KEY ("categoria_id") REFERENCES "public"."epi_categoria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_movimento_estoque" ADD CONSTRAINT "fk_epi_movimento_entrada" FOREIGN KEY ("entrada_id") REFERENCES "public"."epi_entrada_estoque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_movimento_estoque" ADD CONSTRAINT "fk_epi_movimento_requisicao_item" FOREIGN KEY ("requisicao_item_id") REFERENCES "public"."epi_requisicao_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_movimento_estoque" ADD CONSTRAINT "fk_epi_movimento_ficha" FOREIGN KEY ("ficha_registro_id") REFERENCES "public"."epi_ficha_registro"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_movimento_estoque" ADD CONSTRAINT "fk_epi_movimento_registrado_por" FOREIGN KEY ("registrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_servidor" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_solicitado_por" FOREIGN KEY ("solicitado_por_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_chefia" FOREIGN KEY ("chefia_servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_unidade" FOREIGN KEY ("unidade_uorg_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_campus" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_posto" FOREIGN KEY ("posto_trabalho_id") REFERENCES "public"."posto_trabalho"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_analisado_por" FOREIGN KEY ("analisado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao" ADD CONSTRAINT "fk_epi_req_motivo" FOREIGN KEY ("motivo_recusa_id") REFERENCES "public"."epi_motivo_recusa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_req" FOREIGN KEY ("requisicao_id") REFERENCES "public"."epi_requisicao"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_epi" FOREIGN KEY ("epi_item_id") REFERENCES "public"."epi_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_entrada" FOREIGN KEY ("entrada_id") REFERENCES "public"."epi_entrada_estoque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_autorizado_por" FOREIGN KEY ("autorizado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_motivo" FOREIGN KEY ("motivo_recusa_id") REFERENCES "public"."epi_motivo_recusa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "epi_requisicao_item" ADD CONSTRAINT "fk_epi_req_item_decidido_por" FOREIGN KEY ("decidido_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assinatura_instrutor" ADD CONSTRAINT "fk_assinatura_servidor" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assinatura_instrutor" ADD CONSTRAINT "fk_assinatura_imagem" FOREIGN KEY ("imagem_anexo_id") REFERENCES "public"."anexo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_inscricao" FOREIGN KEY ("inscricao_id") REFERENCES "public"."inscricao"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_modelo" FOREIGN KEY ("modelo_id") REFERENCES "public"."certificado_modelo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_pdf" FOREIGN KEY ("arquivo_pdf_anexo_id") REFERENCES "public"."anexo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_servidor" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_campus" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_treinamento" FOREIGN KEY ("treinamento_id") REFERENCES "public"."treinamento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_participante" FOREIGN KEY ("participante_id") REFERENCES "public"."participante"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_emitido_por" FOREIGN KEY ("emitido_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_anulado_por" FOREIGN KEY ("anulado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado" ADD CONSTRAINT "fk_certificado_substituto" FOREIGN KEY ("substituido_por_id") REFERENCES "public"."certificado"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado_modelo" ADD CONSTRAINT "fk_certificado_modelo_treinamento" FOREIGN KEY ("treinamento_id") REFERENCES "public"."treinamento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado_modelo" ADD CONSTRAINT "fk_certificado_modelo_criado_por" FOREIGN KEY ("criado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certificado_modelo_tag" ADD CONSTRAINT "fk_modelo_tag_modelo" FOREIGN KEY ("modelo_id") REFERENCES "public"."certificado_modelo"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscricao" ADD CONSTRAINT "fk_inscricao_turma" FOREIGN KEY ("turma_id") REFERENCES "public"."turma"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscricao" ADD CONSTRAINT "fk_inscricao_participante" FOREIGN KEY ("participante_id") REFERENCES "public"."participante"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscricao" ADD CONSTRAINT "fk_inscricao_inscrito_por" FOREIGN KEY ("inscrito_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscricao" ADD CONSTRAINT "fk_inscricao_confirmada_por" FOREIGN KEY ("confirmada_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participante" ADD CONSTRAINT "fk_participante_servidor" FOREIGN KEY ("servidor_id") REFERENCES "public"."servidor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participante" ADD CONSTRAINT "fk_participante_email_principal" FOREIGN KEY ("email_principal_id") REFERENCES "public"."participante_email"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participante" ADD CONSTRAINT "fk_participante_mesclado" FOREIGN KEY ("mesclado_em_id") REFERENCES "public"."participante"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participante_email" ADD CONSTRAINT "fk_participante_email_dono" FOREIGN KEY ("participante_id") REFERENCES "public"."participante"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "treinamento" ADD CONSTRAINT "fk_treinamento_modelo_vigente" FOREIGN KEY ("modelo_vigente_id") REFERENCES "public"."certificado_modelo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "treinamento" ADD CONSTRAINT "fk_treinamento_instrutor_padrao" FOREIGN KEY ("instrutor_padrao_id") REFERENCES "public"."assinatura_instrutor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma" ADD CONSTRAINT "fk_turma_treinamento" FOREIGN KEY ("treinamento_id") REFERENCES "public"."treinamento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma" ADD CONSTRAINT "fk_turma_campus" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma" ADD CONSTRAINT "fk_turma_unidade" FOREIGN KEY ("unidade_promotora_id") REFERENCES "public"."unidade_uorg"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma" ADD CONSTRAINT "fk_turma_criado_por" FOREIGN KEY ("criado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma_instrutor" ADD CONSTRAINT "fk_turma_instrutor_turma" FOREIGN KEY ("turma_id") REFERENCES "public"."turma"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma_instrutor" ADD CONSTRAINT "fk_turma_instrutor_assinatura" FOREIGN KEY ("assinatura_instrutor_id") REFERENCES "public"."assinatura_instrutor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma_presenca" ADD CONSTRAINT "fk_turma_presenca_inscricao" FOREIGN KEY ("inscricao_id") REFERENCES "public"."inscricao"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turma_presenca" ADD CONSTRAINT "fk_turma_presenca_registrado_por" FOREIGN KEY ("registrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_adicional_vigente" ON "adicional_vigencia" USING btree ("servidor_id") WHERE estado = 'VIGENTE';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_exposicao_principal" ON "exposicao" USING btree ("parecer_id") WHERE principal IS TRUE;--> statement-breakpoint
CREATE INDEX "ix_parecer_ano" ON "parecer_tecnico" USING btree ("ano");--> statement-breakpoint
CREATE INDEX "ix_parecer_processo" ON "parecer_tecnico" USING btree ("processo_id");--> statement-breakpoint
CREATE INDEX "ix_processo_estado" ON "processo" USING btree ("estado_tecnico");--> statement-breakpoint
CREATE INDEX "ix_processo_etapa" ON "processo" USING btree ("etapa_id");--> statement-breakpoint
CREATE INDEX "ix_processo_servidor" ON "processo" USING btree ("servidor_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_processo_origem" ON "processo" USING btree ("origem_migracao","origem_ref") WHERE origem_ref IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_anexo_dedup" ON "anexo" USING btree ("entidade","entidade_id","sha256");--> statement-breakpoint
CREATE INDEX "ix_anexo_sha" ON "anexo" USING btree ("sha256");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_parecer_assinado_ativo" ON "anexo" USING btree ("entidade_id") WHERE entidade = 'parecer_tecnico' AND categoria = 'PARECER_ASSINADO' AND ativo IS TRUE;--> statement-breakpoint
CREATE INDEX "ix_hist_entidade" ON "historico_evento" USING btree ("entidade","entidade_id");--> statement-breakpoint
CREATE INDEX "ix_hist_processo" ON "historico_evento" USING btree ("processo_id");--> statement-breakpoint
CREATE INDEX "ix_hist_ocorrido" ON "historico_evento" USING btree ("ocorrido_em");--> statement-breakpoint
CREATE INDEX "ix_rejeitada_origem" ON "migracao_rejeitada" USING btree ("origem","ref");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_pendencia_chave" ON "pendencia" USING btree ("chave");--> statement-breakpoint
CREATE INDEX "ix_pendencia_aberta" ON "pendencia" USING btree ("concluida","prazo");--> statement-breakpoint
CREATE INDEX "ix_pendencia_entidade" ON "pendencia" USING btree ("entidade","entidade_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_stg_planilha" ON "stg_planilha_parecer" USING btree ("arquivo","linha_origem");--> statement-breakpoint
CREATE INDEX "ix_demanda_estado" ON "demanda" USING btree ("estado","prazo");--> statement-breakpoint
CREATE INDEX "ix_demanda_responsavel" ON "demanda" USING btree ("responsavel_id");--> statement-breakpoint
CREATE INDEX "ix_demanda_servidor" ON "demanda" USING btree ("solicitante_servidor_id");--> statement-breakpoint
CREATE INDEX "ix_demanda_encaminhamento" ON "demanda_encaminhamento" USING btree ("demanda_id");--> statement-breakpoint
CREATE INDEX "ix_entrada_item" ON "epi_entrada_estoque" USING btree ("epi_item_id","tamanho");--> statement-breakpoint
CREATE INDEX "ix_entrada_validade_ca" ON "epi_entrada_estoque" USING btree ("validade_ca");--> statement-breakpoint
CREATE INDEX "ix_entrada_empenho" ON "epi_entrada_estoque" USING btree ("empenho");--> statement-breakpoint
CREATE INDEX "ix_ficha_servidor" ON "epi_ficha_registro" USING btree ("servidor_id","data_evento");--> statement-breakpoint
CREATE INDEX "ix_ficha_item" ON "epi_ficha_registro" USING btree ("epi_item_id");--> statement-breakpoint
CREATE INDEX "ix_ficha_troca" ON "epi_ficha_registro" USING btree ("previsao_troca");--> statement-breakpoint
CREATE INDEX "ix_epi_item_categoria" ON "epi_item" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "ix_epi_item_ativo" ON "epi_item" USING btree ("ativo");--> statement-breakpoint
CREATE INDEX "ix_mov_entrada" ON "epi_movimento_estoque" USING btree ("entrada_id");--> statement-breakpoint
CREATE INDEX "ix_mov_requisicao_item" ON "epi_movimento_estoque" USING btree ("requisicao_item_id");--> statement-breakpoint
CREATE INDEX "ix_req_estado" ON "epi_requisicao" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "ix_req_servidor" ON "epi_requisicao" USING btree ("servidor_id");--> statement-breakpoint
CREATE INDEX "ix_req_unidade" ON "epi_requisicao" USING btree ("unidade_uorg_id");--> statement-breakpoint
CREATE INDEX "ix_req_item_estado" ON "epi_requisicao_item" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "ix_req_item_reserva" ON "epi_requisicao_item" USING btree ("entrada_id","estado");--> statement-breakpoint
CREATE INDEX "ix_req_item_motivo" ON "epi_requisicao_item" USING btree ("motivo_recusa_id");--> statement-breakpoint
CREATE INDEX "ix_assinatura_ativo" ON "assinatura_instrutor" USING btree ("ativo");--> statement-breakpoint
CREATE INDEX "ix_certificado_vencimento" ON "certificado" USING btree ("data_vencimento");--> statement-breakpoint
CREATE INDEX "ix_certificado_servidor" ON "certificado" USING btree ("servidor_id");--> statement-breakpoint
CREATE INDEX "ix_certificado_participante" ON "certificado" USING btree ("participante_id");--> statement-breakpoint
CREATE INDEX "ix_certificado_treinamento" ON "certificado" USING btree ("treinamento_id");--> statement-breakpoint
CREATE INDEX "ix_certificado_inscricao" ON "certificado" USING btree ("inscricao_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_certificado_ativo" ON "certificado" USING btree ("inscricao_id") WHERE situacao <> 'ANULADO';--> statement-breakpoint
CREATE INDEX "ix_modelo_tag_campo" ON "certificado_modelo_tag" USING btree ("campo");--> statement-breakpoint
CREATE INDEX "ix_inscricao_participante" ON "inscricao" USING btree ("participante_id");--> statement-breakpoint
CREATE INDEX "ix_inscricao_turma_situacao" ON "inscricao" USING btree ("turma_id","situacao");--> statement-breakpoint
CREATE INDEX "ix_participante_mesclado" ON "participante" USING btree ("mesclado_em_id");--> statement-breakpoint
CREATE INDEX "ix_participante_email_norm" ON "participante_email" USING btree ("email_normalizado");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_email_confirmado" ON "participante_email" USING btree ("email_normalizado") WHERE confirmado_em IS NOT NULL;--> statement-breakpoint
CREATE INDEX "ix_treinamento_ativo" ON "treinamento" USING btree ("ativo");--> statement-breakpoint
CREATE INDEX "ix_turma_treinamento" ON "turma" USING btree ("treinamento_id");--> statement-breakpoint
CREATE INDEX "ix_turma_situacao" ON "turma" USING btree ("situacao");--> statement-breakpoint
CREATE INDEX "ix_turma_data_fim" ON "turma" USING btree ("data_fim");