"""historico de lotacao e origem da classificacao

Revision ID: ad69609daba3
Revises: 9305283613f3
Create Date: 2026-08-12 12:33:08.717419+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.modelos.base  # noqa: F401  (tipos DataPura/MomentoUTC)

revision: str = 'ad69609daba3'
down_revision: str | None = '9305283613f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor_lotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=True),
    sa.Column('posto_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('funcao', sa.String(length=120), nullable=True),
    sa.Column('vigencia_inicio', app.modelos.base.DataPura(), nullable=False),
    sa.Column('vigencia_fim', app.modelos.base.DataPura(), nullable=True),
    sa.Column('documento', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.CheckConstraint('vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio', name='ck_lotacao_periodo'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['posto_trabalho_id'], ['posto_trabalho.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servidor_id', 'vigencia_inicio', name='uq_lotacao_inicio')
    )
    with op.batch_alter_table('exposicao', schema=None) as batch_op:
        # server_default: a coluna e NOT NULL e a tabela pode ja ter linhas
        batch_op.add_column(
            sa.Column(
                'classificacao_origem',
                sa.String(length=10),
                nullable=False,
                server_default='CALCULADA',
            )
        )
        batch_op.create_check_constraint(
            'ck_class_origem', "classificacao_origem IN ('CALCULADA','INFORMADA')"
        )

    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posto_trabalho_id', sa.Integer(), nullable=True))
        # a FK precisa de nome: sem ele o downgrade nao consegue removê-la
        batch_op.create_foreign_key(
            'fk_servidor_posto', 'posto_trabalho', ['posto_trabalho_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_servidor_posto', type_='foreignkey')
        batch_op.drop_column('posto_trabalho_id')

    with op.batch_alter_table('exposicao', schema=None) as batch_op:
        batch_op.drop_constraint('ck_class_origem', type_='check')
        batch_op.drop_column('classificacao_origem')

    op.drop_table('servidor_lotacao')
    # ### end Alembic commands ###
