"""esquema inicial

Revision ID: 1f1491fbb226
Revises: 
Create Date: 2026-08-11 20:32:12.975202+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.modelos.base  # noqa: F401  (tipos DataPura/MomentoUTC/JSONTexto/Inet)

# `TRIGGERS_ESQUEMA_INICIAL`, e nao `TRIGGERS`: migracao le o passado. Com a
# lista completa, toda trava de modulo futuro passaria a ser criada AQUI — sobre
# tabela que ainda nao existe neste ponto da historia —, e o `upgrade` desde o
# zero quebraria com "no such table". Foi o que aconteceria ao acrescentar as
# travas append-only da ficha de EPI.
from app.banco import TRIGGERS_ESQUEMA_INICIAL as TRIGGERS

revision: str = '1f1491fbb226'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _criar_tabelas()
    _criar_triggers()


def _criar_triggers() -> None:
    """Travas de banco: histórico append-only e RN-01 (IN 15/2022, art. 10, §2º, I)."""
    for nome, ddl in TRIGGERS:
        op.execute(f"DROP TRIGGER IF EXISTS {nome}")
        op.execute(ddl)


def _remover_triggers() -> None:
    for nome, _ in TRIGGERS:
        op.execute(f"DROP TRIGGER IF EXISTS {nome}")


def _criar_tabelas() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoridade_destinataria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('tratamento', sa.String(length=80), nullable=False),
    sa.Column('vigencia_inicio', app.modelos.base.DataPura(), nullable=False),
    sa.Column('vigencia_fim', app.modelos.base.DataPura(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=12), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('avancado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo_siape', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fluxo_etapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('terminal', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('FLUXO','REPOSITORIO')", name='ck_etapa_tipo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ordem')
    )
    op.create_table('migracao_rejeitada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('payload', app.modelos.base.JSONTexto(), nullable=False),
    sa.Column('expurgar_apos', app.modelos.base.DataPura(), nullable=True),
    sa.Column('criado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migracao_rejeitada', schema=None) as batch_op:
        batch_op.create_index('ix_rejeitada_origem', ['origem', 'ref'], unique=False)

    op.create_table('parecer_sequencia',
    sa.Column('ano', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ultimo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ano')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('base_normativa', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('modulo', sa.String(length=32), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('setor_emissor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla_composta', sa.String(length=60), nullable=False),
    sa.Column('nome_extenso', sa.String(length=200), nullable=False),
    sa.Column('unidade_sei', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=60), nullable=True),
    sa.Column('vigencia_inicio', app.modelos.base.DataPura(), nullable=False),
    sa.Column('vigencia_fim', app.modelos.base.DataPura(), nullable=True),
    sa.Column('base_normativa', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla_composta', 'vigencia_inicio', name='uq_setor_vigencia')
    )
    op.create_table('stg_planilha_parecer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('linha_origem', sa.Integer(), nullable=False),
    sa.Column('col_a_data_solicitacao', sa.Text(), nullable=True),
    sa.Column('col_b_numero_parecer', sa.Text(), nullable=True),
    sa.Column('col_c_nome_servidor', sa.Text(), nullable=True),
    sa.Column('col_d_ano', sa.Text(), nullable=True),
    sa.Column('col_e_data', sa.Text(), nullable=True),
    sa.Column('col_f_laudo_de', sa.Text(), nullable=True),
    sa.Column('col_g_unidade', sa.Text(), nullable=True),
    sa.Column('col_h_posto_trabalho', sa.Text(), nullable=True),
    sa.Column('col_i_uorg', sa.Text(), nullable=True),
    sa.Column('col_j_tipo_laudo', sa.Text(), nullable=True),
    sa.Column('col_k_numero_processo', sa.Text(), nullable=True),
    sa.Column('col_l_matricula', sa.Text(), nullable=True),
    sa.Column('col_m_cargo', sa.Text(), nullable=True),
    sa.Column('col_n_funcao', sa.Text(), nullable=True),
    sa.Column('col_o_laudo_siape', sa.Text(), nullable=True),
    sa.Column('col_p_agente_nocivo', sa.Text(), nullable=True),
    sa.Column('col_q_tipo_risco', sa.Text(), nullable=True),
    sa.Column('col_r_percentual', sa.Text(), nullable=True),
    sa.Column('col_s_portaria', sa.Text(), nullable=True),
    sa.Column('col_t_fundamentacao', sa.Text(), nullable=True),
    sa.Column('col_u_alteracao', sa.Text(), nullable=True),
    sa.Column('col_v_recomendacao', sa.Text(), nullable=True),
    sa.Column('col_w_reavaliacao', sa.Text(), nullable=True),
    sa.Column('col_x_pro_reitor', sa.Text(), nullable=True),
    sa.Column('col_Y_sem_cabecalho', sa.Text(), nullable=True),
    sa.Column('classificacao', sa.String(length=12), nullable=True),
    sa.Column('importado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stg_planilha_parecer', schema=None) as batch_op:
        batch_op.create_index('uq_stg_planilha', ['arquivo', 'linha_origem'], unique=True)

    op.create_table('stg_trello_acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=40), nullable=False),
    sa.Column('card_id', sa.String(length=40), nullable=True),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('data', sa.String(length=40), nullable=True),
    sa.Column('autor', sa.String(length=160), nullable=True),
    sa.Column('payload', app.modelos.base.JSONTexto(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('stg_trello_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('lista', sa.Text(), nullable=True),
    sa.Column('payload', app.modelos.base.JSONTexto(), nullable=False),
    sa.Column('parecer_candidato', sa.String(length=12), nullable=True),
    sa.Column('laudo_candidato', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('texto_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('renderizado_pelo_modelo', sa.Boolean(), nullable=False),
    sa.Column('dispositivo_conferido_em', app.modelos.base.DataPura(), nullable=True),
    sa.CheckConstraint("categoria IN ('ALTERACAO','RECOMENDACAO','REAVALIACAO','RODAPE_RESPONSABILIDADE','ASSUNTO','PREAMBULO','ENCERRAMENTO')", name='ck_cat'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria', 'codigo', 'versao', name='uq_texto')
    )
    op.create_table('tipo_adicional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=24), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('nome_recomendacao', sa.String(length=80), nullable=False),
    sa.Column('base_legal', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_marco_inicial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('rotulo', sa.String(length=80), nullable=False),
    sa.Column('base_legal', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('gera_direito', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cor_hex', sa.String(length=7), nullable=True),
    sa.Column('modulo', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('fundamentacao_legal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('norma', sa.String(length=40), nullable=False),
    sa.Column('anexo', sa.String(length=20), nullable=True),
    sa.Column('tipo_risco_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('dispositivo_conferido_em', app.modelos.base.DataPura(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_risco_id'], ['tipo_risco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('percentual_aplicavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_adicional_id', sa.Integer(), nullable=False),
    sa.Column('grau', sa.String(length=10), nullable=False),
    sa.Column('rotulo', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_calculo', sa.String(length=60), nullable=False),
    sa.CheckConstraint("grau IN ('MINIMO','MEDIO','MAXIMO','UNICO')", name='ck_grau'),
    sa.ForeignKeyConstraint(['tipo_adicional_id'], ['tipo_adicional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_adicional_id', 'grau', name='uq_percentual')
    )
    op.create_table('perfil_permissao',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    op.create_table('unidade_uorg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_uorg', sa.String(length=6), nullable=True),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('nome_oficial', sa.String(length=160), nullable=False),
    sa.Column('nome_extenso', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade_pai_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('emite_portaria', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('FACULDADE','INSTITUTO','DEPARTAMENTO','PRO_REITORIA','DIRETORIA','COORDENADORIA','SUPERINTENDENCIA','SECRETARIA','OUTRO')", name='ck_uorg_tipo'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['unidade_pai_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_uorg')
    )
    op.create_table('agente_nocivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo_risco_id', sa.Integer(), nullable=False),
    sa.Column('fundamentacao_id', sa.Integer(), nullable=True),
    sa.Column('percentual_sugerido_id', sa.Integer(), nullable=True),
    sa.Column('exige_reavaliacao_quantitativa', sa.Boolean(), nullable=False),
    sa.Column('agente_canonico_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agente_canonico_id'], ['agente_nocivo.id'], ),
    sa.ForeignKeyConstraint(['fundamentacao_id'], ['fundamentacao_legal.id'], ),
    sa.ForeignKeyConstraint(['percentual_sugerido_id'], ['percentual_aplicavel.id'], ),
    sa.ForeignKeyConstraint(['tipo_risco_id'], ['tipo_risco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('portaria_localizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_emissora_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_publicacao', app.modelos.base.DataPura(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('arquivo_anexo_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("CAST(strftime('%Y', data_publicacao) AS integer) = ano", name='ck_portaria_ano'),
    sa.ForeignKeyConstraint(['unidade_emissora_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_emissora_id', 'numero', 'ano', name='uq_portaria')
    )
    op.create_table('posto_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_uorg_id', 'nome', name='uq_posto')
    )
    op.create_table('servidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siape', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('funcao', sa.String(length=120), nullable=True),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siape')
    )
    op.create_table('portaria_servidor',
    sa.Column('portaria_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('posto_trabalho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portaria_id'], ['portaria_localizacao.id'], ),
    sa.ForeignKeyConstraint(['posto_trabalho_id'], ['posto_trabalho.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.PrimaryKeyConstraint('portaria_id', 'servidor_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('provedor', sa.String(length=16), nullable=False),
    sa.Column('identificador_externo', sa.String(length=120), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativas_falhas', sa.SmallInteger(), nullable=False),
    sa.Column('bloqueado_ate', app.modelos.base.MomentoUTC(), nullable=True),
    sa.Column('ultimo_login_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.Column('criado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.CheckConstraint("provedor IN ('LOCAL','LDAP','SSO_UFVJM')", name='ck_usuario_provedor'),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=30), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('nivel_acesso', sa.String(length=12), nullable=False),
    sa.Column('numero_documento_sei', sa.String(length=10), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('origem_migracao', sa.String(length=20), nullable=True),
    sa.Column('origem_ref', sa.String(length=200), nullable=True),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.Column('enviado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.CheckConstraint("categoria IN ('PARECER_ASSINADO','LAUDO','PORTARIA','DESPACHO','FORMULARIO','RELATORIO_CAMPO','FOTO','OUTRO')", name='ck_anexo_cat'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.create_index('ix_anexo_sha', ['sha256'], unique=False)
        batch_op.create_index('uq_anexo_dedup', ['entidade', 'entidade_id', 'sha256'], unique=True)
        batch_op.create_index('uq_parecer_assinado_ativo', ['entidade_id'], unique=True, sqlite_where=sa.text("entidade = 'parecer_tecnico' AND categoria = 'PARECER_ASSINADO' AND ativo IS 1"), postgresql_where=sa.text("entidade = 'parecer_tecnico' AND categoria = 'PARECER_ASSINADO' AND ativo IS 1"))

    op.create_table('atribuicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('coordenadoria', sa.String(length=16), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('vigencia_inicio', app.modelos.base.DataPura(), nullable=False),
    sa.Column('vigencia_fim', app.modelos.base.DataPura(), nullable=True),
    sa.Column('ato_normativo', sa.Text(), nullable=True),
    sa.Column('concedido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['concedido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nup', sa.String(length=20), nullable=False),
    sa.Column('tipo_processo_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('estado_tecnico', sa.String(length=32), nullable=False),
    sa.Column('estado_anterior', sa.String(length=32), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('ano_referencia', sa.Integer(), nullable=True),
    sa.Column('data_solicitacao_sest', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_autuacao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('prazo', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_conclusao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('nivel_acesso', sa.String(length=12), nullable=False),
    sa.Column('acompanhamento_especial', sa.Boolean(), nullable=False),
    sa.Column('pronto_para_emissao', sa.Boolean(), nullable=False),
    sa.Column('origem_repositorio', sa.Boolean(), nullable=False),
    sa.Column('url_permanente', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('nup_dv_dispensado', sa.Boolean(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('origem_migracao', sa.String(length=20), nullable=True),
    sa.Column('origem_ref', sa.String(length=64), nullable=True),
    sa.Column('entrou_na_etapa_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('criado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('atualizado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.CheckConstraint("(situacao = 'CONCLUIDO') = (data_conclusao IS NOT NULL)", name='ck_conclusao'),
    sa.CheckConstraint("estado_tecnico IN ('NAO_INICIADO','RECEBIDO','EM_TRIAGEM','PENDENTE_DOCUMENTO','AGUARDANDO_INSPECAO','INSPECIONADO','AGUARDANDO_QUANTIFICACAO','LAUDO_EM_ELABORACAO','LAUDO_EMITIDO','PARECER_EM_ELABORACAO','PARECER_PRONTO_P_ASSINATURA','PARECER_ASSINADO','INSERIDO_NO_SEI','DEVOLVIDO_A_PROGEP','CONCLUIDO','INDEFERIDO_TECNICAMENTE','ARQUIVADO','SOBRESTADO','EM_RECURSO')", name='ck_estado_tecnico'),
    sa.CheckConstraint("nivel_acesso IN ('PUBLICO','RESTRITO','SIGILOSO')", name='ck_acesso'),
    sa.ForeignKeyConstraint(['etapa_id'], ['fluxo_etapa.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['tipo_processo_id'], ['tipo_processo.id'], ),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nup')
    )
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.create_index('ix_processo_estado', ['estado_tecnico'], unique=False)
        batch_op.create_index('ix_processo_etapa', ['etapa_id'], unique=False)
        batch_op.create_index('ix_processo_servidor', ['servidor_id'], unique=False)
        batch_op.create_index('uq_processo_origem', ['origem_migracao', 'origem_ref'], unique=True, sqlite_where=sa.text('origem_ref IS NOT NULL'), postgresql_where=sa.text('origem_ref IS NOT NULL'))

    op.create_table('profissional_habilitado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('siape', sa.String(length=7), nullable=True),
    sa.Column('habilitacao', sa.String(length=30), nullable=False),
    sa.Column('titulo_assinatura', sa.String(length=60), nullable=False),
    sa.Column('conselho', sa.String(length=8), nullable=True),
    sa.Column('registro_conselho', sa.String(length=30), nullable=True),
    sa.Column('documento_especializacao', sa.String(length=120), nullable=True),
    sa.Column('externo', sa.Boolean(), nullable=False),
    sa.Column('justificativa_art10_par5', sa.Text(), nullable=True),
    sa.Column('vigencia_inicio', app.modelos.base.DataPura(), nullable=False),
    sa.Column('vigencia_fim', app.modelos.base.DataPura(), nullable=True),
    sa.Column('atestado_por', sa.Integer(), nullable=True),
    sa.Column('atestado_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.CheckConstraint("habilitacao IN ('MED_TRABALHO','ENG_SEG_TRABALHO','ARQ_SEG_TRABALHO')", name='ck_habilitacao'),
    sa.CheckConstraint('externo = 0 OR justificativa_art10_par5 IS NOT NULL', name='ck_externo'),
    sa.ForeignKeyConstraint(['atestado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('expira_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('ip', app.modelos.base.Inet(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revogada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('acesso_dado_sensivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=60), nullable=False),
    sa.Column('finalidade', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_evento',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entidade', sa.String(length=30), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('campo', sa.String(length=60), nullable=True),
    sa.Column('valor_anterior', app.modelos.base.JSONTexto(), nullable=True),
    sa.Column('valor_novo', app.modelos.base.JSONTexto(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=160), nullable=False),
    sa.Column('ocorrido_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('registrado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('origem_ref', sa.String(length=64), nullable=True),
    sa.Column('ip', app.modelos.base.Inet(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_atual', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_evento', schema=None) as batch_op:
        batch_op.create_index('ix_hist_entidade', ['entidade', 'entidade_id'], unique=False)
        batch_op.create_index('ix_hist_ocorrido', ['ocorrido_em'], unique=False)
        batch_op.create_index('ix_hist_processo', ['processo_id'], unique=False)

    op.create_table('laudo_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_siape', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo_adicional_id', sa.Integer(), nullable=False),
    sa.Column('coletivo', sa.Boolean(), nullable=False),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_avaliacao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_ultima_conferencia', app.modelos.base.DataPura(), nullable=True),
    sa.Column('motivo_ultima_conferencia', sa.Text(), nullable=True),
    sa.Column('subscritor_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('numero_documento_sei', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('substituido_por_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.CheckConstraint("status IN ('VIGENTE','SUPERADO')", name='ck_laudo_status'),
    sa.CheckConstraint('ano = CAST(substr(numero_siape,15,4) AS integer)', name='ck_laudo_ano'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['subscritor_id'], ['profissional_habilitado.id'], ),
    sa.ForeignKeyConstraint(['substituido_por_id'], ['laudo_tecnico.id'], ),
    sa.ForeignKeyConstraint(['tipo_adicional_id'], ['tipo_adicional.id'], ),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_siape')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('concluido_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.Column('concluido_por', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concluido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laudo_posto',
    sa.Column('laudo_id', sa.Integer(), nullable=False),
    sa.Column('posto_trabalho_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudo_tecnico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posto_trabalho_id'], ['posto_trabalho.id'], ),
    sa.PrimaryKeyConstraint('laudo_id', 'posto_trabalho_id')
    )
    op.create_table('parecer_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_emissao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('situacao', sa.String(length=15), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('laudo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_adicional_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimento_id', sa.Integer(), nullable=True),
    sa.Column('unidade_uorg_id', sa.Integer(), nullable=True),
    sa.Column('portaria_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('signatario_id', sa.Integer(), nullable=True),
    sa.Column('setor_emissor_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('parecer_anterior_id', sa.Integer(), nullable=True),
    sa.Column('cargo_snapshot', sa.String(length=120), nullable=True),
    sa.Column('funcao_snapshot', sa.String(length=120), nullable=True),
    sa.Column('sigla_emissora_snapshot', sa.String(length=60), nullable=True),
    sa.Column('nome_emissor_snapshot', sa.String(length=200), nullable=True),
    sa.Column('endereco_emissor_snapshot', sa.Text(), nullable=True),
    sa.Column('telefone_emissor_snapshot', sa.String(length=60), nullable=True),
    sa.Column('tipo_marco_id', sa.Integer(), nullable=True),
    sa.Column('data_marco_inicial', app.modelos.base.DataPura(), nullable=True),
    sa.Column('justificativa_marco', sa.Text(), nullable=True),
    sa.Column('texto_recomendacao', sa.Text(), nullable=True),
    sa.Column('texto_alteracao', sa.Text(), nullable=True),
    sa.Column('texto_reavaliacao', sa.Text(), nullable=True),
    sa.Column('texto_rodape', sa.Text(), nullable=True),
    sa.Column('texto_recomendacao_literal', sa.Boolean(), nullable=False),
    sa.Column('modelo_arquivo', sa.String(length=120), nullable=True),
    sa.Column('modelo_sha256', sa.String(length=64), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('horas_semanais_fonte', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('portaria_designacao_dirigente_id', sa.Integer(), nullable=True),
    sa.Column('area_radiologica', sa.String(length=16), nullable=True),
    sa.Column('arquivo_docx_id', sa.Integer(), nullable=True),
    sa.Column('arquivo_pdf_id', sa.Integer(), nullable=True),
    sa.Column('numero_documento_sei', sa.String(length=10), nullable=True),
    sa.Column('motivo_anulacao', sa.Text(), nullable=True),
    sa.Column('origem_migracao', sa.String(length=20), nullable=True),
    sa.Column('origem_ref', sa.String(length=64), nullable=True),
    sa.Column('ano_inferido', sa.Boolean(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('emitido_por', sa.Integer(), nullable=True),
    sa.Column('emitido_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.Column('assinado_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.CheckConstraint("area_radiologica IS NULL OR area_radiologica IN ('CONTROLADA','SUPERVISIONADA')", name='ck_area'),
    sa.CheckConstraint("data_emissao IS NULL OR CAST(strftime('%Y', data_emissao) AS integer) = ano", name='ck_data_ano'),
    sa.CheckConstraint("situacao <> 'ANULADO' OR motivo_anulacao IS NOT NULL", name='ck_anulado'),
    sa.CheckConstraint("situacao IN ('RESERVADO','RASCUNHO','EM_REVISAO','EMITIDO','ASSINADO','ANULADO')", name='ck_situacao'),
    sa.CheckConstraint("situacao NOT IN ('EMITIDO','ASSINADO') OR (servidor_id IS NOT NULL AND laudo_id IS NOT NULL AND data_emissao IS NOT NULL AND signatario_id IS NOT NULL AND destinatario_id IS NOT NULL AND portaria_id IS NOT NULL AND processo_id IS NOT NULL AND tipo_adicional_id IS NOT NULL AND tipo_movimento_id IS NOT NULL AND unidade_uorg_id IS NOT NULL AND texto_recomendacao IS NOT NULL AND tipo_marco_id IS NOT NULL AND data_marco_inicial IS NOT NULL)", name='ck_completo'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['autoridade_destinataria.id'], ),
    sa.ForeignKeyConstraint(['emitido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudo_tecnico.id'], ),
    sa.ForeignKeyConstraint(['parecer_anterior_id'], ['parecer_tecnico.id'], ),
    sa.ForeignKeyConstraint(['portaria_id'], ['portaria_localizacao.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['setor_emissor_id'], ['setor_emissor.id'], ),
    sa.ForeignKeyConstraint(['signatario_id'], ['profissional_habilitado.id'], ),
    sa.ForeignKeyConstraint(['tipo_adicional_id'], ['tipo_adicional.id'], ),
    sa.ForeignKeyConstraint(['tipo_marco_id'], ['tipo_marco_inicial.id'], ),
    sa.ForeignKeyConstraint(['tipo_movimento_id'], ['tipo_movimento.id'], ),
    sa.ForeignKeyConstraint(['unidade_uorg_id'], ['unidade_uorg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'ano', name='uq_parecer')
    )
    with op.batch_alter_table('parecer_tecnico', schema=None) as batch_op:
        batch_op.create_index('ix_parecer_ano', ['ano'], unique=False)
        batch_op.create_index('ix_parecer_processo', ['processo_id'], unique=False)

    op.create_table('adicional_vigencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('parecer_id', sa.Integer(), nullable=False),
    sa.Column('tipo_adicional_id', sa.Integer(), nullable=False),
    sa.Column('percentual_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('portaria_concessao', sa.String(length=120), nullable=True),
    sa.Column('data_portaria_concessao', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_inicio', app.modelos.base.DataPura(), nullable=True),
    sa.Column('data_fim', app.modelos.base.DataPura(), nullable=True),
    sa.Column('motivo_suspensao', sa.String(length=30), nullable=True),
    sa.Column('base_legal_suspensao', sa.String(length=120), nullable=True),
    sa.Column('registro_opcao_anexo_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado IN ('PROPOSTO','VIGENTE','SUSPENSO','EM_REAVALIACAO','ALTERADO','CESSADO')", name='ck_estado'),
    sa.CheckConstraint("motivo_suspensao IS NULL OR motivo_suspensao IN ('CESSACAO_RISCO','AFASTAMENTO_DO_LOCAL','AFASTAMENTO_LEGAL','DECISAO_ADMINISTRATIVA')", name='ck_motivo_susp'),
    sa.ForeignKeyConstraint(['parecer_id'], ['parecer_tecnico.id'], ),
    sa.ForeignKeyConstraint(['percentual_id'], ['percentual_aplicavel.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ),
    sa.ForeignKeyConstraint(['tipo_adicional_id'], ['tipo_adicional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adicional_vigencia', schema=None) as batch_op:
        batch_op.create_index('uq_adicional_vigente', ['servidor_id'], unique=True, sqlite_where=sa.text("estado = 'VIGENTE'"), postgresql_where=sa.text("estado = 'VIGENTE'"))

    op.create_table('exposicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parecer_id', sa.Integer(), nullable=False),
    sa.Column('agente_nocivo_id', sa.Integer(), nullable=False),
    sa.Column('percentual_id', sa.Integer(), nullable=False),
    sa.Column('fundamentacao_id', sa.Integer(), nullable=False),
    sa.Column('posto_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('tempo_exposicao', sa.String(length=60), nullable=True),
    sa.Column('horas_exposicao_mensais', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('jornada_mensal_horas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percentual_jornada', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('classificacao_exposicao', sa.String(length=16), nullable=True),
    sa.Column('excecao_art9_par_unico', sa.Boolean(), nullable=False),
    sa.Column('justificativa_art9', sa.Text(), nullable=True),
    sa.Column('intensidade', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('limite_tolerancia', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('metodologia', sa.String(length=120), nullable=True),
    sa.Column('data_avaliacao', app.modelos.base.DataPura(), nullable=True),
    sa.CheckConstraint("classificacao_exposicao IS NULL OR classificacao_exposicao IN ('EVENTUAL','HABITUAL','PERMANENTE')", name='ck_exposicao'),
    sa.CheckConstraint('excecao_art9_par_unico = 0 OR justificativa_art9 IS NOT NULL', name='ck_excecao'),
    sa.ForeignKeyConstraint(['agente_nocivo_id'], ['agente_nocivo.id'], ),
    sa.ForeignKeyConstraint(['fundamentacao_id'], ['fundamentacao_legal.id'], ),
    sa.ForeignKeyConstraint(['parecer_id'], ['parecer_tecnico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['percentual_id'], ['percentual_aplicavel.id'], ),
    sa.ForeignKeyConstraint(['posto_trabalho_id'], ['posto_trabalho.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parecer_id', 'agente_nocivo_id', name='uq_exposicao')
    )
    with op.batch_alter_table('exposicao', schema=None) as batch_op:
        batch_op.create_index('uq_exposicao_principal', ['parecer_id'], unique=True, sqlite_where=sa.text('principal IS 1'), postgresql_where=sa.text('principal IS 1'))

    op.create_table('parecer_posto',
    sa.Column('parecer_id', sa.Integer(), nullable=False),
    sa.Column('posto_trabalho_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parecer_id'], ['parecer_tecnico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posto_trabalho_id'], ['posto_trabalho.id'], ),
    sa.PrimaryKeyConstraint('parecer_id', 'posto_trabalho_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    _remover_triggers()
    _remover_tabelas()


def _remover_tabelas() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parecer_posto')
    with op.batch_alter_table('exposicao', schema=None) as batch_op:
        batch_op.drop_index('uq_exposicao_principal', sqlite_where=sa.text('principal IS 1'), postgresql_where=sa.text('principal IS 1'))

    op.drop_table('exposicao')
    with op.batch_alter_table('adicional_vigencia', schema=None) as batch_op:
        batch_op.drop_index('uq_adicional_vigente', sqlite_where=sa.text("estado = 'VIGENTE'"), postgresql_where=sa.text("estado = 'VIGENTE'"))

    op.drop_table('adicional_vigencia')
    with op.batch_alter_table('parecer_tecnico', schema=None) as batch_op:
        batch_op.drop_index('ix_parecer_processo')
        batch_op.drop_index('ix_parecer_ano')

    op.drop_table('parecer_tecnico')
    op.drop_table('laudo_posto')
    op.drop_table('checklist_item')
    op.drop_table('laudo_tecnico')
    with op.batch_alter_table('historico_evento', schema=None) as batch_op:
        batch_op.drop_index('ix_hist_processo')
        batch_op.drop_index('ix_hist_ocorrido')
        batch_op.drop_index('ix_hist_entidade')

    op.drop_table('historico_evento')
    op.drop_table('checklist')
    op.drop_table('acesso_dado_sensivel')
    op.drop_table('sessao')
    op.drop_table('profissional_habilitado')
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.drop_index('uq_processo_origem', sqlite_where=sa.text('origem_ref IS NOT NULL'), postgresql_where=sa.text('origem_ref IS NOT NULL'))
        batch_op.drop_index('ix_processo_servidor')
        batch_op.drop_index('ix_processo_etapa')
        batch_op.drop_index('ix_processo_estado')

    op.drop_table('processo')
    op.drop_table('atribuicao')
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.drop_index('uq_parecer_assinado_ativo', sqlite_where=sa.text("entidade = 'parecer_tecnico' AND categoria = 'PARECER_ASSINADO' AND ativo IS 1"), postgresql_where=sa.text("entidade = 'parecer_tecnico' AND categoria = 'PARECER_ASSINADO' AND ativo IS 1"))
        batch_op.drop_index('uq_anexo_dedup')
        batch_op.drop_index('ix_anexo_sha')

    op.drop_table('anexo')
    op.drop_table('usuario')
    op.drop_table('portaria_servidor')
    op.drop_table('servidor')
    op.drop_table('posto_trabalho')
    op.drop_table('portaria_localizacao')
    op.drop_table('agente_nocivo')
    op.drop_table('unidade_uorg')
    op.drop_table('perfil_permissao')
    op.drop_table('percentual_aplicavel')
    op.drop_table('fundamentacao_legal')
    op.drop_table('tipo_risco')
    op.drop_table('tipo_processo')
    op.drop_table('tipo_movimento')
    op.drop_table('tipo_marco_inicial')
    op.drop_table('tipo_adicional')
    op.drop_table('texto_padrao')
    op.drop_table('stg_trello_cartao')
    op.drop_table('stg_trello_acao')
    with op.batch_alter_table('stg_planilha_parecer', schema=None) as batch_op:
        batch_op.drop_index('uq_stg_planilha')

    op.drop_table('stg_planilha_parecer')
    op.drop_table('setor_emissor')
    op.drop_table('permissao')
    op.drop_table('perfil')
    op.drop_table('parecer_sequencia')
    with op.batch_alter_table('migracao_rejeitada', schema=None) as batch_op:
        batch_op.drop_index('ix_rejeitada_origem')

    op.drop_table('migracao_rejeitada')
    op.drop_table('fluxo_etapa')
    op.drop_table('cargo')
    op.drop_table('campus')
    op.drop_table('autoridade_destinataria')
    # ### end Alembic commands ###
