"""congelar o contexto do parecer na emissao

Revision ID: b4a719a434de
Revises: ad69609daba3
Create Date: 2026-08-12 14:41:33.729016+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.modelos.base  # noqa: F401  (tipo JSONTexto)

revision: str = 'b4a719a434de'
down_revision: str | None = 'ad69609daba3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parecer_tecnico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contexto_congelado', app.modelos.base.JSONTexto(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parecer_tecnico', schema=None) as batch_op:
        batch_op.drop_column('contexto_congelado')

    # ### end Alembic commands ###
