"""pendencia com dono e prazo

Revision ID: 63457c0b908f
Revises: 1f1491fbb226
Create Date: 2026-08-11 21:43:49.436992+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.modelos.base  # noqa: F401  (tipos DataPura/MomentoUTC)

revision: str = '63457c0b908f'
down_revision: str | None = '1f1491fbb226'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('parecer_id', sa.Integer(), nullable=True),
    sa.Column('laudo_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('prazo', app.modelos.base.DataPura(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('concluida_em', app.modelos.base.MomentoUTC(), nullable=True),
    sa.Column('concluida_por', sa.Integer(), nullable=True),
    sa.Column('criada_em', app.modelos.base.MomentoUTC(), nullable=False),
    sa.Column('chave', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['concluida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudo_tecnico.id'], ),
    sa.ForeignKeyConstraint(['parecer_id'], ['parecer_tecnico.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.create_index('ix_pendencia_aberta', ['concluida', 'prazo'], unique=False)
        batch_op.create_index('uq_pendencia_chave', ['chave'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.drop_index('uq_pendencia_chave')
        batch_op.drop_index('ix_pendencia_aberta')

    op.drop_table('pendencia')
    # ### end Alembic commands ###
