"""parametro e checklist modelo

Revision ID: 9305283613f3
Revises: 63457c0b908f
Create Date: 2026-08-11 22:16:15.078175+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9305283613f3'
down_revision: str | None = '63457c0b908f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('checklist_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo_processo_id', sa.Integer(), nullable=True),
    sa.Column('estado_alvo', sa.String(length=32), nullable=True),
    sa.Column('itens', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_processo_id'], ['tipo_processo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_modelo')
    op.drop_table('parametro')
    # ### end Alembic commands ###
